/// Capture privacy regression tests (docs/05-authority-kernel.md §6.1;
/// V1-Verified/03d `concealed-type-leak-flat-schema`). Concealment is a
/// pasteboard-item property, not an independently retainable representation:
/// either the explicit HistoryCore observation flag or any known sibling
/// marker rejects the whole capture before fingerprinting.
import Foundation
import HistoryCore
import Testing
@testable import HistoryStorage

private let ingestExclusionMarkers: [String] = [
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
    "de.petermaurer.TransientPasteboardType",
    "org.nspasteboard.AutoGeneratedType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
]

struct IngestPreparationPrivacyTests {

private static func capture(
    marker: String? = nil,
    isConcealed: Bool = false
) -> ClipboardCapture {
    var representations = [CapturedRepresentation(
        typeIdentifier: "public.utf8-plain-text",
        bytes: Data("credential-value".utf8)
    )]
    if let marker {
        // Marker payloads are commonly empty. Privacy rejection must precede
        // ordinary per-representation byte validation so the whole item is
        // classified consistently and never reaches fingerprinting.
        representations.append(CapturedRepresentation(
            typeIdentifier: marker,
            bytes: Data()
        ))
    }
    return ClipboardCapture(
        representations: representations,
        origin: CopyOriginObservation(
            sourceApplication: "com.example.password-manager",
            lineageHint: nil
        ),
        observedAt: Date(timeIntervalSinceReferenceDate: 700_100_000),
        isConcealed: isConcealed
    )
}

@Test func standardExclusionMarkerSetIsComplete() {
    #expect(
        IngestPreparationActor.standardTransientTypeIdentifiers
            == Set(ingestExclusionMarkers)
    )
}

@Test func explicitConcealmentIsRejectedBeforeFingerprinting() async {
    let preparation = IngestPreparationActor(fingerprint: { _ in
        Issue.record("A concealed capture reached representation fingerprinting")
        return 0
    })

    await #expect(throws: HistoryFailure.invalidInput(.excludedFromHistory)) {
        try await preparation.prepare(Self.capture(isConcealed: true))
    }
}

@Test(arguments: ingestExclusionMarkers)
func siblingExclusionMarkerRejectsWholeCaptureBeforeFingerprinting(
    marker: String
) async {
    let preparation = IngestPreparationActor(fingerprint: { _ in
        Issue.record("An excluded capture reached representation fingerprinting")
        return 0
    })

    await #expect(throws: HistoryFailure.invalidInput(.excludedFromHistory)) {
        try await preparation.prepare(Self.capture(marker: marker))
    }
}

@Test func concealedSiblingMarkerNeverCreatesRetainedHistory() async throws {
    let history = try await SwiftDataHistory.open(
        configuration: HistoryConfiguration(persistence: .memory)
    )

    await #expect(throws: HistoryFailure.invalidInput(.excludedFromHistory)) {
        try await history.perform(.capture(Self.capture(
            marker: "org.nspasteboard.ConcealedType"
        )))
    }

    let page = try await history.browse(HistoryBrowseRequest(
        kind: .recent,
        limit: 50
    ))
    #expect(page.rows.isEmpty)
    #expect(page.position == .zero)
}
}
