/// RenderStormAndMemoryTests — real-scale tripwires for the COMPOSED stack
/// (real `SwiftDataHistory` + real `HistoryViewState`/`ThumbnailStore` over
/// HistoryCore DTOs, per `ComposedSupport.swift`): render-storm observation
/// coalescing, a search-debounce storm, a resident-memory leak tripwire,
/// and activate/deactivate cancellation hygiene.
///
/// These suites guard the docs/06-cross-cutting.md §2 resource ceilings'
/// behavioral side — the UI/storage loop stays BOUNDED under stress — rather
/// than re-measuring the ceilings themselves (the timed proofs live in Part
/// VI §9's runner). Nothing here asserts timing: every wait is a
/// generous-but-bounded `ComposedSupport.waitFor`, and the memory test is a
/// leak tripwire with deliberate CI-runner-variance slack.
///
/// Only the debounce-storm and memory tests touch the `clipy-fixtures-v1`
/// tree (generated by `scripts/generate_fixtures.py`, hosted on the
/// `fixtures-v1` release, fetched by `scripts/fetch_fixtures.sh`); both are
/// gated with `.enabled(if: FixtureCatalog.available, ...)` so a fresh
/// clone's test run stays green — on CI the fetch step fails the job on any
/// download error, so a silent skip there is impossible (FixtureCatalog.swift).
import Darwin
import Foundation
import HistoryCore
import HistoryStorage
import PresentationUI
import Testing

/// `.serialized`: the memory tripwire reads PROCESS-wide RSS, so the four
/// tests (and especially the seeding/rounds of the memory test) must not
/// overlap each other inside this suite.
@Suite("Render-storm / memory tripwires (fixtures-v1 where gated)", .serialized)
struct RenderStormAndMemoryTests {

    /// Render-storm coalescing (docs/04-coherence.md §4 newest-only
    /// invalidation buffering + §5 position-recheck page freshness; the
    /// stress twin of WS12 in docs/06-cross-cutting.md §8): an ACTIVATED
    /// view state and a second, independent page-counting `observe` stream
    /// face 100 back-to-back capture commits. The counting stream must
    /// never deliver MORE pages than commits plus the stream's one initial
    /// snapshot — superseded positions are dropped by the
    /// `.bufferingNewest(1)` wake-up buffer and the §5 discard-and-requery
    /// recheck — while still converging on the newest position, and the
    /// view state's replacement pages (§5: snapshots, never deltas) reach
    /// the complete 100-row page.
    @Test @MainActor
    func renderStormCoalescesToFewerPagesThanCommits() async throws {
        let commitTotal = 100
        let history = try await ComposedSupport.openMemoryHistory()
        // One page holds the whole storm: 100 rows is inside the Part VI
        // page/observation row-limit range 1…500 (docs/06-cross-cutting.md §2).
        let viewState = HistoryViewState(history: history, pageLimit: commitTotal)
        defer { viewState.deactivate() }

        // The page-counting consumer: a second observation of the same query
        // shape, consumed by an unstructured task. Created inside a MainActor
        // test, the task inherits the MainActor (the same pattern
        // `HistoryViewState.restartObservation` uses), so `log` needs no
        // synchronization of its own.
        let log = PagePositionLog()
        let counter = Task {
            let stream = await history.observe(
                HistoryObservationRequest(kind: .recent, limit: commitTotal)
            )
            do {
                for try await page in stream {
                    if Task.isCancelled { break }
                    log.record(page)
                }
            } catch is CancellationError {
                // Cancelled by the test after convergence — expected.
            } catch {
                Issue.record("render storm: counting stream failed: \(error)")
            }
        }
        defer { counter.cancel() }

        viewState.activate()

        // The storm: distinct small texts (synthetic — this slice needs no
        // fixture), each awaited so every receipt is a real History Commit,
        // fired with no pacing between them.
        let base = Date(timeIntervalSinceReferenceDate: 700_203_000)
        var ids: [HistoryItemID] = []
        var lastPosition: ChangePosition?
        var commitCount = 0
        for index in 0..<commitTotal {
            let receipt = try await history.perform(.capture(
                ComposedSupport.textCapture(
                    "render storm item \(index)",
                    observedAt: base.addingTimeInterval(Double(index) * 0.25),
                    source: "com.example.renderstorm"
                )
            ))
            guard let commit = ComposedSupport.commit(
                of: receipt, "render storm capture \(index)"
            ) else { continue }
            commitCount += 1
            lastPosition = commit.position
            if let reference = ComposedSupport.insertedReference(
                from: receipt, "render storm capture \(index)"
            ) {
                ids.append(reference.id)
            }
        }
        let finalPosition = try #require(lastPosition)
        #expect(commitCount == commitTotal)
        #expect(ids.count == commitTotal)

        // Convergence: snapshot replacement reaches the complete 100-row
        // page (04 §5) — newest-first by recency (05 §14.1).
        let converged = await ComposedSupport.waitFor(timeout: 5) {
            viewState.rows.count == commitTotal
                && Set(viewState.rows.map(\.item.id)) == Set(ids)
        }
        #expect(
            converged,
            "render storm: the view state converges on the final complete page"
        )
        #expect(viewState.failure == nil)

        // The counting stream converges on the newest position too
        // (03b §11 item 5 guarantee), then the anti-storm tripwire:
        // delivered pages never EXCEED commits + the stream's initial
        // snapshot — the initial page may land before the storm's first
        // commit is consumed, adding exactly one delivery beyond the
        // per-commit upper bound (observed as 101 pages for 100 commits on
        // a saturated runner). No amplification, no duplicate-per-commit
        // storm. Equality is legal here: the captures above are awaited
        // sequentially, so the pipeline may publish one page per commit on
        // a fast runner. The deterministic newest-wins coalescing proof
        // itself lives in the storage-side WS12 suspension-point suites
        // (04 §4–§5), which control the interleaving exactly; this
        // composed check is the no-runaway tripwire plus the convergence
        // guarantee.
        let deliveredFinal = await ComposedSupport.waitFor(timeout: 5) {
            log.positions.last == finalPosition
        }
        counter.cancel()
        _ = await counter.value
        #expect(
            deliveredFinal,
            "render storm: the counting observation reaches the newest position"
        )
        #expect(
            log.positions.count <= commitCount + 1,
            "render storm (04 §4–§5): \(log.positions.count) pages for \(commitCount) commits — pages must never exceed commits + the initial snapshot"
        )
    }

    /// Debounce storm (V2-07 §4's 250 ms debounce; docs/
    /// 03b-instruction-set.md §8 exact-mode literal substring over the
    /// bounded stored search body; 04 §5 replacement): 60 synchronous
    /// `searchText` edits collapse into ONE debounced observation restart
    /// whose page answers the FINAL query, and a manual `refresh()` after
    /// settling re-observes the identical row ids with no mixed state at any
    /// poll inside the window.
    ///
    /// The final query is a 48-character window taken from the mid-body of
    /// the 300 KiB `searchbody` fixture — character offset 120_000 sits well
    /// inside the 256 KiB stored-search-body bound (06 §2;
    /// `HistoryLimits.standard.maximumStoredSearchBodyUTF8Bytes`), so the
    /// phrase exercises BODY search (title miss → `searchBody` hit, 03b §8),
    /// not the title fast path.
    @Test(
        .enabled(
            if: FixtureCatalog.available,
            "requires the clipy-fixtures-v1 tree (CLIPY_FIXTURES_DIR)"
        )
    )
    @MainActor
    func searchDebounceStormSettlesOnTheFinalQuery() async throws {
        let history = try await ComposedSupport.openMemoryHistory()
        let viewState = HistoryViewState(history: history)
        defer { viewState.deactivate() }

        let bodyText = try FixtureCatalog.text("text/searchbody-300kb.txt")
        guard bodyText.count > 120_100 else {
            Issue.record(
                "fixture: searchbody-300kb.txt holds the mid-body phrase window"
            )
            return
        }
        let windowStart = bodyText.index(bodyText.startIndex, offsetBy: 120_000)
        let windowEnd = bodyText.index(windowStart, offsetBy: 48)
        let phrase = String(bodyText[windowStart..<windowEnd])

        // One fixture-scale item plus three small fillers whose vocabulary
        // cannot contain the phrase (exact mode is a literal substring
        // match, 03b §8).
        let base = Date(timeIntervalSinceReferenceDate: 700_203_100)
        let fixtureReceipt = try await history.perform(.capture(
            ComposedSupport.textCapture(
                bodyText,
                observedAt: base,
                source: "com.example.debouncestorm"
            )
        ))
        let fixtureID = try #require(
            ComposedSupport.insertedReference(
                from: fixtureReceipt, "debounce storm fixture seed"
            )
        ).id
        for index in 0..<3 {
            _ = try await history.perform(.capture(
                ComposedSupport.textCapture(
                    "debounce storm filler zzz \(index)",
                    observedAt: base.addingTimeInterval(Double(index + 1)),
                    source: "com.example.debouncestorm"
                )
            ))
        }

        viewState.activate()
        let seeded = await ComposedSupport.waitFor(timeout: 3) {
            viewState.rows.count == 4
        }
        #expect(seeded, "debounce storm: the seeded recent page is observed")

        viewState.searchMode = .exact
        // The storm: 60 edits in one synchronous MainActor run — the loop
        // never suspends, so every 250 ms debounce task but the last is
        // cancelled before it can fire (V2-07 §4: no per-keystroke
        // re-observe). Prefixes of the final phrase keep every would-be
        // intermediate query well-formed.
        for index in 0..<60 {
            viewState.searchText = String(phrase.prefix(index % 48 + 1))
        }
        viewState.searchText = phrase

        let settled = await ComposedSupport.waitFor(timeout: 5) {
            viewState.rows.count == 1
                && viewState.rows.first?.item.id == fixtureID
        }
        #expect(
            settled,
            "debounce storm: the settled page answers the FINAL query only"
        )
        #expect(viewState.failure == nil)

        // Self-consistency: a manual refresh restarts observation for the
        // same query; the current rows stay as the baseline until the fresh
        // page replaces them, and that page carries the SAME row ids — no
        // mixed intermediate state at any poll inside the window (04 §5).
        let settledIDs = viewState.rows.map(\.item.id)
        viewState.refresh()
        let refreshWindowEnd = Date().addingTimeInterval(0.8)
        var stayedConsistent = true
        while Date() < refreshWindowEnd {
            if viewState.rows.map(\.item.id) != settledIDs {
                stayedConsistent = false
                break
            }
            try? await Task.sleep(for: .milliseconds(10))
        }
        #expect(
            stayedConsistent,
            "debounce storm: a manual refresh reproduces the settled row ids exactly"
        )
        #expect(viewState.failure == nil)
    }

    /// Memory tripwire (docs/06-cross-cutting.md §2 resource ceilings; 04 §9
    /// thumbnail single-flight + reference-exact cache): seed ~40 items
    /// including the real-scale 4K/8K raster fixtures, then run 5 rounds of
    /// browse first page → details of the heaviest image items →
    /// `ThumbnailStore` prefetch + whole-cache reset → search round trip,
    /// comparing resident memory between the settled post-round-1 baseline
    /// and the settled end.
    ///
    /// This is a LEAK tripwire, never a performance gate: the 400 MiB bound
    /// is deliberately generous because CI-runner RSS varies with allocator
    /// behaviour, autorelease-pool drain timing, and system ImageIO caches;
    /// no timing is asserted anywhere in the suite (Part VI §9 owns the
    /// timed proofs).
    @Test(
        .enabled(
            if: FixtureCatalog.available,
            "requires the clipy-fixtures-v1 tree (CLIPY_FIXTURES_DIR)"
        )
    )
    @MainActor
    func residentMemoryStaysBoundedAcrossRepeatedPanelRounds() async throws {
        let history = try await ComposedSupport.openMemoryHistory()
        let viewState = HistoryViewState(history: history)
        defer { viewState.deactivate() }
        viewState.searchMode = .exact

        let base = Date(timeIntervalSinceReferenceDate: 700_203_200)
        // 34 distinct small texts, all containing the round's search term.
        for index in 0..<34 {
            _ = try await history.perform(.capture(
                ComposedSupport.textCapture(
                    "memory tripwire seed \(index)",
                    observedAt: base.addingTimeInterval(Double(index)),
                    source: "com.example.memorytripwire"
                )
            ))
        }
        // The real-scale rasters (fixtures-v1 manifest.json): 4K PNG/JPEG/
        // TIFF, a 1080p BMP (the largest single representation, ~6 MiB), the
        // 8K PNG thumbnail-stress ceiling case, and an icon-scale PNG.
        let imageFixtures: [(path: String, uti: String)] = [
            ("images/photo4k-a.png", "public.png"),
            ("images/photo4k-b.jpg", "public.jpeg"),
            ("images/photo4k-c.tiff", "public.tiff"),
            ("images/photo-1080.bmp", "com.microsoft.bmp"),
            ("images/huge-8k.png", "public.png"),
            ("images/icon-512.png", "public.png"),
        ]
        var imageIDs: [HistoryItemID] = []
        for (offset, fixture) in imageFixtures.enumerated() {
            let receipt = try await history.perform(.capture(
                ClipboardCapture(
                    representations: [CapturedRepresentation(
                        typeIdentifier: fixture.uti,
                        bytes: try FixtureCatalog.data(fixture.path)
                    )],
                    origin: CopyOriginObservation(
                        sourceApplication: "com.example.memorytripwire",
                        lineageHint: nil
                    ),
                    observedAt: base.addingTimeInterval(1_000 + Double(offset))
                )
            ))
            if let reference = ComposedSupport.insertedReference(
                from: receipt, "memory tripwire image seed \(fixture.path)"
            ) {
                imageIDs.append(reference.id)
            }
        }
        #expect(imageIDs.count == imageFixtures.count)

        let thumbnails = ThumbnailStore(history: history)
        viewState.activate()
        let seeded = await ComposedSupport.waitFor(timeout: 5) {
            viewState.rows.count == 40
        }
        #expect(seeded, "memory tripwire: the seeded 40-row page is observed")

        var baseline: UInt64 = 0
        for round in 1...5 {
            // Browse the first page through the public seam (03a §7).
            let page = try await history.browse(
                HistoryBrowseRequest(kind: .recent, limit: 50)
            )
            #expect(page.rows.count == 40)

            // Details of the two heaviest image items pull their full
            // lineage bytes across the boundary each round (03b §9).
            _ = try await viewState.details(for: imageIDs[3])
            _ = try await viewState.details(for: imageIDs[4])

            // Thumbnail prefetch → ImageIO decode OFF the MainActor
            // (PresentationUI's internal `DisplayImageDecoder` actor —
            // audit 2026-08-20 §S-2/§SPEC-IMPL-002) → bounded-store reset
            // (04 §9; the byte/entry admission bound of audit §S-3); the
            // reset releases the round's retained decoded images so the
            // store itself cannot mask a leak.
            let imageRows = page.rows.filter {
                ThumbnailStore.likelyThumbnailable($0.typeIdentifiers)
            }
            #expect(imageRows.count == imageFixtures.count)
            for row in imageRows {
                thumbnails.prefetch(row.item)
            }
            let decoded = await ComposedSupport.waitFor(timeout: 30) {
                imageRows.allSatisfy { thumbnails.image(for: $0.item) != nil }
            }
            #expect(
                decoded,
                "memory tripwire round \(round): every image row decoded a thumbnail"
            )
            thumbnails.reset()

            // Search → clear: one debounced observation round trip.
            viewState.searchText = "tripwire"
            let searched = await ComposedSupport.waitFor(timeout: 5) {
                viewState.rows.count == 34
            }
            #expect(searched, "memory tripwire round \(round): search page")
            viewState.searchText = ""
            let restored = await ComposedSupport.waitFor(timeout: 5) {
                viewState.rows.count == 40
            }
            #expect(restored, "memory tripwire round \(round): recent page restored")

            // Let the round's transient allocations settle before reading
            // RSS; the baseline is taken only after round 1 so one-time
            // warm-up costs stay out of the comparison.
            try? await Task.sleep(for: .milliseconds(300))
            if round == 1 {
                baseline = ResidentMemoryProbe.bytes()
            }
        }
        #expect(baseline > 0, "memory tripwire: the RSS probe answered")

        let final = ResidentMemoryProbe.bytes()
        let growth = final > baseline ? final - baseline : 0
        #expect(
            growth < 400 * 1_048_576,
            "memory tripwire: settled RSS grew \(growth / 1_048_576) MiB across rounds 2–5 (leak tripwire bound: 400 MiB)"
        )
        #expect(viewState.failure == nil)
    }

    /// Cancellation hygiene (docs/04-coherence.md §5: "cancellation
    /// unregisters the continuation and releases query/search tasks"; 05
    /// §14.4: "cancellation removes the token"): ten
    /// activate → search → deactivate cycles with alternating query shapes
    /// must leave no live streams behind. Proven indirectly: every cycle's
    /// freshly activated loop still converges on the expected page (a leaked
    /// producer pile-up would degrade or corrupt later cycles), and after
    /// the FINAL `deactivate()` a new commit produces no row mutation inside
    /// a bounded window (a leaked loop would keep replacing rows).
    @Test @MainActor
    func activateDeactivateCyclesLeaveNoLiveObservationBehind() async throws {
        let history = try await ComposedSupport.openMemoryHistory()
        let viewState = HistoryViewState(history: history)
        defer { viewState.deactivate() }
        viewState.searchMode = .exact

        let base = Date(timeIntervalSinceReferenceDate: 700_203_300)
        var needleIDs: [HistoryItemID] = []
        for index in 0..<3 {
            let receipt = try await history.perform(.capture(
                ComposedSupport.textCapture(
                    "hygiene needle \(index)",
                    observedAt: base.addingTimeInterval(Double(index)),
                    source: "com.example.cancellationhygiene"
                )
            ))
            if let reference = ComposedSupport.insertedReference(
                from: receipt, "hygiene needle seed \(index)"
            ) {
                needleIDs.append(reference.id)
            }
        }
        for index in 0..<3 {
            _ = try await history.perform(.capture(
                ComposedSupport.textCapture(
                    "hygiene filler \(index)",
                    observedAt: base.addingTimeInterval(100 + Double(index)),
                    source: "com.example.cancellationhygiene"
                )
            ))
        }
        #expect(needleIDs.count == 3)

        // Ten cycles, alternating the query shape so each activation
        // re-observes something different from the previous cycle's tail.
        for cycle in 0..<10 {
            let searching = cycle.isMultiple(of: 2)
            viewState.activate()
            viewState.searchText = searching ? "hygiene needle" : ""
            let converged = await ComposedSupport.waitFor(timeout: 3) {
                searching
                    ? Set(viewState.rows.map(\.item.id)) == Set(needleIDs)
                    : viewState.rows.count == 6
            }
            #expect(converged, "cancellation hygiene: cycle \(cycle) converges")
            viewState.deactivate()
        }
        #expect(viewState.failure == nil)

        // The post-deactivate window: with no live observation, a commit
        // must not move the rows (04 §5; 05 §14.4). A bounded absence check,
        // not a timing assertion.
        let frozenIDs = viewState.rows.map(\.item.id)
        _ = try await history.perform(.capture(
            ComposedSupport.textCapture(
                "hygiene late commit",
                observedAt: base.addingTimeInterval(200),
                source: "com.example.cancellationhygiene"
            )
        ))
        let windowEnd = Date().addingTimeInterval(0.5)
        var stayedFrozen = true
        while Date() < windowEnd {
            if viewState.rows.map(\.item.id) != frozenIDs {
                stayedFrozen = false
                break
            }
            try? await Task.sleep(for: .milliseconds(10))
        }
        #expect(
            stayedFrozen,
            "cancellation hygiene (04 §5): rows stay put after deactivate — no leaked observation loop"
        )
    }
}

/// The page-counting observation's sink for the render-storm test: one
/// MainActor-owned array of delivered page positions. Both the counting
/// task (a MainActor-inherited unstructured task) and the polling test run
/// on the MainActor, so the log needs no actor or lock of its own.
@MainActor
private final class PagePositionLog {
    private(set) var positions: [ChangePosition] = []

    func record(_ page: HistoryPage) {
        positions.append(page.position)
    }
}

/// A tiny resident-memory probe confined to this file: one Darwin
/// `task_info` call (`MACH_TASK_BASIC_INFO`) returning the task's resident
/// size in bytes, or 0 when the kernel call fails. Used only by the leak
/// tripwire above; never a timing or performance instrument.
private enum ResidentMemoryProbe {
    static func bytes() -> UInt64 {
        var info = mach_task_basic_info()
        var count = mach_msg_type_number_t(
            MemoryLayout<mach_task_basic_info>.size
                / MemoryLayout<integer_t>.size
        )
        let status = withUnsafeMutablePointer(to: &info) { pointer in
            pointer.withMemoryRebound(
                to: integer_t.self,
                capacity: Int(count)
            ) { taskInfo in
                task_info(
                    mach_task_self_,
                    task_flavor_t(MACH_TASK_BASIC_INFO),
                    taskInfo,
                    &count
                )
            }
        }
        guard status == KERN_SUCCESS else { return 0 }
        return info.resident_size
    }
}
