/// UISmokeJourneyTests — real-scale UI smoke journeys over the fetched
/// `clipy-fixtures-v1` tree (docs/06-cross-cutting.md §8 walking-skeleton
/// spirit re-run at real payload scale; fixtures generated by
/// `scripts/generate_fixtures.py`, hosted on the `fixtures-v1` release,
/// fetched by `scripts/fetch_fixtures.sh` into `CLIPY_FIXTURES_DIR`).
///
/// Where the WS1–WS21 composed suites pin frozen semantics with tiny
/// synthetic values, these journeys drive the SAME composed stack — the real
/// `SwiftDataHistory` over an in-memory store (docs/05-authority-kernel.md
/// §2), the real @MainActor `HistoryViewState` / `ThumbnailStore`
/// (docs/01-architecture.md §6), and a PRIVATE `NSPasteboard` (never
/// `.general`) where pasteboard I/O is needed — against real-scale payloads:
/// 100 KB–5 MB texts, a 4K JPEG, and the twelve crop images (manifest.json).
///
/// The suite is gated with `.enabled(if: FixtureCatalog.available)` so a
/// fresh clone's test run stays green; CI always fetches the tree (the fetch
/// step fails the job on any download or checksum failure, so a silent skip
/// on CI is impossible). Every async convergence goes through
/// `ComposedSupport.waitFor`; nothing here prints, so the workflow's log
/// self-scan stays quiet.
///
/// Runtime budget (macOS runner): journey 1 dominates with 132 in-memory
/// capture transactions (xxh3 fingerprint + one `ModelContext.transaction`
/// each, 05 §2); journeys 2/4 hold at most one 5 MiB fixture decode in
/// memory; journey 3 thumbnails one 4K JPEG twice. The suite stays well
/// under three minutes.
import AppKit
import CoreGraphics
import Foundation
import HistoryCore
import HistoryStorage
import PasteboardAdapter
import PresentationUI
import Testing

@Suite(
    "UI smoke journeys over the real-scale fixture tree (fixtures-v1)",
    .enabled(
        if: FixtureCatalog.available,
        "requires the fetched clipy-fixtures-v1 tree (CLIPY_FIXTURES_DIR)"
    )
)
@MainActor
struct UISmokeJourneyTests {

    /// Journey 1 — library browse smoke (docs/06-cross-cutting.md §8;
    /// docs/04-coherence.md §5/§6; docs/03b-instruction-set.md §8): seed 120
    /// text items as DISTINCT fixture slices (the per-index slice length
    /// makes byte-level duplication impossible, so no capture can coalesce)
    /// plus all twelve crop images through real `.capture` actions
    /// (03a §4/§5), activate the view state, prove the pinned and recency
    /// lanes populate with pinned rows leading (05 §14.1), then paginate
    /// `loadNextPage()` to exhaustion under a hard iteration cap — the
    /// termination proof — and assert no duplicate row IDs across pages
    /// (04 §6: no overlap, no gap).
    @Test
    func libraryBrowseSmokePaginatesRealScaleSeedWithoutDuplicates() async throws {
        let history = try await ComposedSupport.openMemoryHistory()
        let base = Date(timeIntervalSinceReferenceDate: 700_300_000)

        // Seed 120 distinct text slices. Every slice is far below the 64 MiB
        // representation bound (06 §2); lengths 200...319 are pairwise
        // distinct, so byte counts differ and every receipt is .inserted,
        // never .coalesced (02 §5.4 two-stage dedup never fires).
        let sliceSources = [
            "text/code-swift-200kb.txt",
            "text/markdown-300kb.md",
            "text/json-1mb.json",
            "text/searchbody-300kb.txt",
        ]
        let texts = try sliceSources.map { try FixtureCatalog.text($0) }
        var seededIDs: [HistoryItemID] = []
        for index in 0..<120 {
            let text = texts[index % texts.count]
            let length = 200 + index
            let maxStart = max(0, text.count - length - 1)
            let offset = maxStart == 0 ? 0 : (index * 977) % maxStart
            let slice = String(text.dropFirst(offset).prefix(length))
            let receipt = try await history.perform(.capture(
                ComposedSupport.textCapture(
                    slice,
                    observedAt: base.addingTimeInterval(Double(index)),
                    source: "com.example.uismoke.browse"
                )
            ))
            seededIDs.append(try #require(
                ComposedSupport.insertedReference(from: receipt, "browse seed \(index)")
            ).id)
        }

        // Seed all twelve crop images (manifest.json images/crop-*) as real
        // raster bytes under their frozen v1 UTIs (04 §9).
        let crops: [(path: String, uti: String)] = [
            ("images/crop-01-1600x900.png", "public.png"),
            ("images/crop-02-1024x1024.jpg", "public.jpeg"),
            ("images/crop-03-640x360.png", "public.png"),
            ("images/crop-04-1600x900.jpg", "public.jpeg"),
            ("images/crop-05-1024x1024.png", "public.png"),
            ("images/crop-06-640x360.jpg", "public.jpeg"),
            ("images/crop-07-1600x900.png", "public.png"),
            ("images/crop-08-1024x1024.jpg", "public.jpeg"),
            ("images/crop-09-640x360.png", "public.png"),
            ("images/crop-10-1600x900.jpg", "public.jpeg"),
            ("images/crop-11-1024x1024.png", "public.png"),
            ("images/crop-12-640x360.jpg", "public.jpeg"),
        ]
        for (offset, crop) in crops.enumerated() {
            let bytes = try FixtureCatalog.data(crop.path)
            let receipt = try await history.perform(.capture(ClipboardCapture(
                representations: [CapturedRepresentation(
                    typeIdentifier: crop.uti,
                    bytes: bytes
                )],
                origin: CopyOriginObservation(
                    sourceApplication: "com.example.uismoke.browse",
                    lineageHint: nil
                ),
                observedAt: base.addingTimeInterval(Double(120 + offset))
            )))
            seededIDs.append(try #require(
                ComposedSupport.insertedReference(from: receipt, "browse crop \(crop.path)")
            ).id)
        }
        #expect(seededIDs.count == 132, "browse smoke: 120 slices + 12 crops seeded")

        let viewState = HistoryViewState(history: history) // default pageLimit 50
        defer { viewState.deactivate() }
        viewState.activate()

        let firstPage = await ComposedSupport.waitFor(timeout: 10) {
            viewState.rows.count == 50 && viewState.hasNextPage
        }
        #expect(
            firstPage,
            "browse smoke: the observed first page holds 50 rows with a cursor"
        )

        // Pin two items through the panel surface (03a §5): each commit
        // replaces the observed page (04 §5), pinned lane first (05 §14.1).
        let pinA = seededIDs[10]
        let pinB = seededIDs[70]
        viewState.pin(pinA, at: .last)
        viewState.pin(pinB, at: .last)
        let lanesSettled = await ComposedSupport.waitFor(timeout: 10) {
            viewState.pinnedRows.count == 2 && viewState.rows.count == 50
        }
        #expect(lanesSettled, "browse smoke: the pinned lane populates")
        #expect(
            viewState.rows.prefix(2).map(\.item.id) == [pinA, pinB],
            "browse smoke (05 §14.1): pinned rows lead in placement order"
        )
        #expect(
            viewState.unpinnedRows.count == 48,
            "browse smoke: the recency lane holds the rest of the first page"
        )

        // Paginate to exhaustion under a hard cap (termination proof): with
        // 132 rows and a 50-row limit the loop must finish in 2 iterations;
        // the cap of 8 fails descriptively if continuation ever stalls.
        var iterations = 0
        let iterationCap = 8
        while viewState.hasNextPage, iterations < iterationCap {
            let displayed = viewState.rows.count
            viewState.loadNextPage()
            let appended = await ComposedSupport.waitFor(timeout: 10) {
                viewState.rows.count > displayed || !viewState.hasNextPage
            }
            #expect(
                appended,
                "browse smoke: continuation page \(iterations + 1) landed"
            )
            iterations += 1
        }
        #expect(
            iterations < iterationCap,
            "browse smoke (04 §6): pagination terminated well under the cap"
        )
        #expect(!viewState.hasNextPage, "browse smoke: the cursor is exhausted")
        #expect(viewState.rows.count == 132, "browse smoke: every seeded row displayed")

        // No overlap, no gap (04 §6): every seeded ID appears exactly once.
        let displayedIDs = viewState.rows.map(\.item.id)
        #expect(
            Set(displayedIDs).count == displayedIDs.count,
            "browse smoke (04 §6): no duplicate row IDs across pages"
        )
        #expect(Set(displayedIDs) == Set(seededIDs))
        #expect(viewState.pinnedRows.count == 2)
        #expect(viewState.unpinnedRows.count == 130)
        #expect(viewState.failure == nil)
    }

    /// Journey 2 — search smoke (docs/03b-instruction-set.md §8/§10;
    /// docs/06-cross-cutting.md §2): over a REAL 200 KiB Swift-source capture
    /// (fully inside the 256 KiB stored-search-body bound), an exact phrase
    /// query selects the item and every `SearchPresentation` UTF-16 range
    /// indexes valid String indices of its snippet-or-title base; a fuzzy
    /// query for a short title word (absent from every text fixture, so the
    /// result set is unambiguous) ranks its row first; a safe anchored
    /// regexp matches; and an invalid pattern surfaces
    /// `.invalidInput(.invalidRegularExpression)` in the panel's typed
    /// failure banner (03b §10).
    @Test
    func searchSmokeExactFuzzyRegexpAndInvalidPatternOverFixtures() async throws {
        let history = try await ComposedSupport.openMemoryHistory()
        let base = Date(timeIntervalSinceReferenceDate: 700_301_000)

        let codeText = try FixtureCatalog.text("text/code-swift-200kb.txt")
        let codeReceipt = try await history.perform(.capture(
            ComposedSupport.textCapture(
                codeText,
                observedAt: base,
                source: "com.example.uismoke.search"
            )
        ))
        let codeID = try #require(
            ComposedSupport.insertedReference(from: codeReceipt, "search seed code")
        ).id

        // The fuzzy/regexp target: "journey" appears in NO text fixture
        // (verified against the generated tree), so each mode's result set
        // is unambiguous.
        let journeyReceipt = try await history.perform(.capture(
            ComposedSupport.textCapture(
                "fixture journey settings panel",
                observedAt: base.addingTimeInterval(1),
                source: "com.example.uismoke.search"
            )
        ))
        let journeyID = try #require(
            ComposedSupport.insertedReference(from: journeyReceipt, "search seed journey")
        ).id

        _ = try await history.perform(.capture(
            ComposedSupport.textCapture(
                "ui smoke decoy plain row",
                observedAt: base.addingTimeInterval(2),
                source: "com.example.uismoke.search"
            )
        ))

        let viewState = HistoryViewState(history: history)
        defer { viewState.deactivate() }
        viewState.activate()

        // Exact (03b §8): a distinctive phrase carried by
        // code-swift-200kb.txt near the top of the file.
        let phrase = "release-like performance runner for the Part VI §9"
        viewState.searchMode = .exact
        viewState.searchText = phrase
        let exactSettled = await ComposedSupport.waitFor(timeout: 10) {
            viewState.rows.map(\.item.id) == [codeID]
                && viewState.rows.allSatisfy { $0.search != nil }
        }
        #expect(
            exactSettled,
            "search smoke exact: the phrase selects the code item alone"
        )
        let exactRow = try #require(viewState.rows.first)
        // 03b §8: ranges annotate the TITLE when snippet == nil, else the
        // SNIPPET — the base is whichever the row carries.
        let exactBase = exactRow.search?.snippet ?? exactRow.title
        let exactRanges = exactRow.search?.matchedRanges ?? []
        #expect(
            !exactRanges.isEmpty,
            "search smoke exact: the match carries UTF-16 ranges"
        )
        for range in exactRanges {
            #expect(
                ComposedSupport.substring(exactBase, utf16Range: range).lowercased()
                    == phrase.lowercased(),
                "search smoke exact (03b §8): every range indexes the matched phrase"
            )
        }

        // Fuzzy (03b §8; Fuse 1.4.0): the short title word matches the
        // journey row's TITLE (a title match carries snippet == nil).
        viewState.searchMode = .fuzzy
        viewState.searchText = "journey"
        let fuzzySettled = await ComposedSupport.waitFor(timeout: 10) {
            viewState.rows.map(\.item.id) == [journeyID]
                && viewState.rows.allSatisfy { $0.search != nil }
        }
        #expect(
            fuzzySettled,
            "search smoke fuzzy: the title word selects the journey row alone"
        )
        #expect(
            viewState.rows.first?.search?.snippet == nil,
            "search smoke fuzzy (03b §8): a title match carries no snippet"
        )

        // Regexp (03b §8): a safe anchored pattern; the invalid pattern then
        // fails closed into the panel banner (03b §10).
        viewState.searchMode = .regexp
        viewState.searchText = "^fixture journey"
        let regexpSettled = await ComposedSupport.waitFor(timeout: 10) {
            viewState.rows.map(\.item.id) == [journeyID]
        }
        #expect(regexpSettled, "search smoke regexp: the anchored pattern matches")

        viewState.searchText = "(unclosed"
        let failureSurfaced = await ComposedSupport.waitFor(timeout: 10) {
            viewState.failure == .invalidInput(.invalidRegularExpression)
        }
        #expect(
            failureSurfaced,
            "search smoke regexp (03b §10): the invalid pattern surfaces the typed failure"
        )
    }

    /// Journey 3 — image detail smoke (docs/03b-instruction-set.md §9;
    /// docs/04-coherence.md §9): a REAL 4K JPEG (images/photo4k-b.jpg,
    /// 189,348 bytes per manifest.json) frozen from a PRIVATE pasteboard by
    /// the real adapter; details expose the stored bytes unchanged; the real
    /// `ThumbnailStore` materializes an eager raster inside the requested 72 px
    /// box; and the reference-exact fence holds — after a byte-changing
    /// revision, the reference at the NEW Content Version never sees the old
    /// pixels, then fetches its own.
    @Test
    func imageDetailSmokeMaterializesThumbnailWithVersionFence() async throws {
        try ComposedSupport.requireUsablePasteboard()
        let history = try await ComposedSupport.openMemoryHistory()

        let jpegBytes = try FixtureCatalog.data("images/photo4k-b.jpg")
        let pasteboard = ComposedSupport.makePasteboard()
        pasteboard.clearContents()
        pasteboard.setData(
            jpegBytes,
            forType: NSPasteboard.PasteboardType("public.jpeg")
        )
        let adapter = PasteboardAdapter(pasteboard: pasteboard)
        let capture = try #require(
            adapter.capture(
                observedAt: Date(timeIntervalSinceReferenceDate: 700_302_000)
            ),
            "image smoke: the JPEG freeze yields a capture"
        )
        #expect(
            capture.representations.first?.typeIdentifier == "public.jpeg",
            "image smoke: the JPEG representation survives the freeze"
        )

        let insertReceipt = try await history.perform(.capture(capture))
        let inserted = try #require(
            ComposedSupport.insertedReference(from: insertReceipt, "image smoke arrange")
        )

        let viewState = HistoryViewState(history: history)
        let details = try await viewState.details(for: inserted.id)
        #expect(details.effective.count == 1)
        #expect(details.effective.first?.typeIdentifier == "public.jpeg")
        #expect(
            details.effective.first?.bytes == jpegBytes,
            "image smoke (03b §9): details return the captured bytes unchanged"
        )

        // The UTI heuristic admits the row (04 §9), the size read never
        // fetches, and `prefetch` lands decoded pixels in the 72 px box.
        let store = ThumbnailStore(history: history)
        #expect(
            ThumbnailStore.likelyThumbnailable(["public.jpeg"]),
            "image smoke: the heuristic admits the JPEG row"
        )
        #expect(store.imagePixelSize(for: inserted) == nil)
        store.prefetch(inserted)
        let decoded = await ComposedSupport.waitFor(timeout: 15) {
            store.imagePixelSize(for: inserted) != nil
        }
        #expect(decoded, "image smoke: the 4K JPEG thumbnail materialized")
        let image = try #require(store.imagePixelSize(for: inserted))
        #expect(image.width > 0 && image.width <= 72)
        #expect(image.height > 0 && image.height <= 72)

        // The fence (04 §9): revise with a different real JPEG
        // (crop-02-1024x1024.jpg); the new reference must NOT see the
        // cached pixels, then prefetches its own.
        let replacement = try FixtureCatalog.data("images/crop-02-1024x1024.jpg")
        let reviseReceipt = try await viewState.revise(RevisionRequest(
            itemID: inserted.id,
            expected: inserted.contentVersion,
            intent: .replace(RevisionDraft(decisions: [
                RevisionDecision(
                    typeIdentifier: "public.jpeg",
                    action: .replace(bytes: replacement)
                ),
            ]))
        ))
        let revised = try #require(
            ComposedSupport.revisedReference(from: reviseReceipt, "image smoke revise")
        )
        #expect(revised.contentVersion != inserted.contentVersion)
        #expect(
            store.imagePixelSize(for: revised) == nil,
            "image smoke (04 §9): a revised reference never inherits stale pixels"
        )
        #expect(
            store.imagePixelSize(for: inserted) != nil,
            "image smoke (04 §9): the old key keeps its own pixels"
        )
        store.prefetch(revised)
        let revisedDecoded = await ComposedSupport.waitFor(timeout: 15) {
            store.imagePixelSize(for: revised) != nil
        }
        #expect(
            revisedDecoded,
            "image smoke: the revised reference fetched its own pixels"
        )
    }

    /// Journey 4 — revise smoke (docs/03a-instruction-set.md §5;
    /// docs/03b-instruction-set.md §9; docs/04-coherence.md §2): revising a
    /// 200 KiB text item, replacing its bytes with a 120,000-Character slice
    /// of lorem-5mb.txt, commits `.revised`, advances the Content Version by
    /// exactly one (Effective Content bytes changed), and the detail read
    /// shows the NEW effective bytes while the canonical lineage keeps the
    /// original capture bytes.
    @Test
    func reviseSmokeReplacesBytesAndAdvancesContentVersion() async throws {
        let history = try await ComposedSupport.openMemoryHistory()

        let codeText = try FixtureCatalog.text("text/code-swift-200kb.txt")
        #expect(
            codeText.utf8.count > 100_000,
            "revise smoke: the base item is 100 KB+ of real text"
        )
        let insertReceipt = try await history.perform(.capture(
            ComposedSupport.textCapture(
                codeText,
                observedAt: Date(timeIntervalSinceReferenceDate: 700_303_000),
                source: "com.example.uismoke.revise"
            )
        ))
        let inserted = try #require(
            ComposedSupport.insertedReference(from: insertReceipt, "revise smoke arrange")
        )

        let lorem = try FixtureCatalog.text("text/lorem-5mb.txt")
        let slice = String(lorem.prefix(120_000))
        let newBytes = Data(slice.utf8)
        #expect(newBytes != Data(codeText.utf8))

        let viewState = HistoryViewState(history: history)
        let receipt = try await viewState.revise(RevisionRequest(
            itemID: inserted.id,
            expected: inserted.contentVersion,
            intent: .replace(RevisionDraft(decisions: [
                RevisionDecision(
                    typeIdentifier: ComposedSupport.plainTextTypeIdentifier,
                    action: .replace(bytes: newBytes)
                ),
            ]))
        ))
        let revised = try #require(
            ComposedSupport.revisedReference(from: receipt, "revise smoke revise")
        )
        #expect(revised.id == inserted.id)
        #expect(
            revised.contentVersion.rawValue == inserted.contentVersion.rawValue + 1,
            "revise smoke (04 §2): the Content Version advances exactly once"
        )

        let details = try await viewState.details(for: inserted.id)
        #expect(details.item.contentVersion == revised.contentVersion)
        #expect(details.effective.count == 1)
        #expect(
            details.effective.first?.bytes == newBytes,
            "revise smoke (03b §9): details show the new effective bytes"
        )
        #expect(
            details.canonical.first?.bytes == Data(codeText.utf8),
            "revise smoke (03a §5): canonical lineage keeps the captured bytes"
        )
        #expect(details.revisions.count == 1)
        #expect(details.revisions.first?.isActive == true)
    }

    /// Journey 5 — settings smoke (docs/02-domain.md §12;
    /// docs/06-cross-cutting.md §8 WS21; docs/v2/V2-02-retention.md §3.1):
    /// the settings Apply path `applyMaximumUnpinnedItems(40)` over 50 seeded
    /// unpinned items commits `.retentionPolicySet(removedCount: 10)`,
    /// retiring the ten OLDEST (02 §12 eviction order), and the V2-02
    /// age+storage bundle applies as one `.retentionPoliciesSet` commit that
    /// retires nothing — both dimensions are deliberately satisfied (the
    /// seeded items are years younger than the 3,600-day age fence; retained
    /// bytes are far under the 512 MiB storage fence; both values are inside
    /// the §8.3 admission ranges).
    @Test
    func settingsSmokeAppliesCountCapAndPolicyBundle() async throws {
        let history = try await ComposedSupport.openMemoryHistory()
        let base = Date(timeIntervalSinceReferenceDate: 700_304_000)
        var seededIDs: [HistoryItemID] = []
        for index in 0..<50 {
            let receipt = try await history.perform(.capture(
                ComposedSupport.textCapture(
                    "ui smoke settings item \(index)",
                    observedAt: base.addingTimeInterval(Double(index)),
                    source: "com.example.uismoke.settings"
                )
            ))
            seededIDs.append(try #require(
                ComposedSupport.insertedReference(from: receipt, "settings seed \(index)")
            ).id)
        }

        let viewState = HistoryViewState(history: history) // pageLimit 50
        defer { viewState.deactivate() }
        viewState.activate()
        let populated = await ComposedSupport.waitFor(timeout: 10) {
            viewState.rows.count == 50 && !viewState.hasNextPage
        }
        #expect(populated, "settings smoke: all 50 rows observed on one page")

        // v1 count dimension (02 §12): cap 40 retires the ten oldest
        // unpinned items in ONE commit.
        let lowered = try await viewState.applyMaximumUnpinnedItems(40)
        let commit = try #require(
            ComposedSupport.commit(of: lowered, "settings smoke cap"),
            "settings smoke: the cap lowering is a History Commit"
        )
        guard case let .retentionPolicySet(removedCount) = commit.outcome else {
            Issue.record(
                "settings smoke: expected .retentionPolicySet, got \(commit.outcome)"
            )
            return
        }
        #expect(
            removedCount == 10,
            "settings smoke (02 §12): the ten oldest retired"
        )
        let retired = await ComposedSupport.waitFor(timeout: 10) {
            viewState.rows.count == 40
        }
        #expect(retired, "settings smoke: the panel observes the retired set")
        #expect(
            Set(viewState.rows.map(\.item.id)) == Set(seededIDs.suffix(40)),
            "settings smoke (02 §12): the newest 40 survived"
        )

        // V2-02 bundle (§3.1; DC-23 — one policy value, per-dimension
        // disable): age + storage enabled, revision dimension disabled.
        let bundle = try await viewState.applyRetentionPolicies(
            HistoryRetentionPolicies(
                age: AgeRetention(maxAge: 3_600 * 86_400),
                storage: StorageRetention(maxTotalBytes: 512 * 1_048_576),
                revisions: nil
            )
        )
        let bundleCommit = try #require(
            ComposedSupport.commit(of: bundle, "settings smoke bundle"),
            "settings smoke: the policy bundle is a History Commit"
        )
        guard case let .retentionPoliciesSet(retiredItems, prunedRevisions)
                = bundleCommit.outcome else {
            Issue.record(
                "settings smoke: expected .retentionPoliciesSet, got \(bundleCommit.outcome)"
            )
            return
        }
        #expect(
            retiredItems == 0,
            "settings smoke (V2-02 §3.1): the satisfied bundle retires no item"
        )
        #expect(prunedRevisions == 0)
        #expect(viewState.failure == nil)
    }
}
