/// FixtureCatalog — locates the unpacked `clipy-fixtures-v1` release tree
/// for the real-scale stress/smoke suites (generated by
/// `scripts/generate_fixtures.py`, hosted on the `fixtures-v1` GitHub
/// release, fetched by `scripts/fetch_fixtures.sh`).
///
/// Suites gate themselves with `.enabled(if: FixtureCatalog.available)` so a
/// fresh clone's `swift test` stays green; CI always fetches the tree (the
/// fetch step fails the job on any download or checksum error, so a silent
/// skip on CI is impossible).
///
/// This file is intentionally duplicated across test targets — SwiftPM test
/// targets cannot share code without a new library target, and the loader is
/// deliberately tiny (06 §8 test-independence spirit). Keep the copies
/// byte-identical: Tests/HistoryStorageTests, Tests/PasteboardAdapterTests,
/// Tests/ContentPreviewTests, ClipyApp/Tests/ClipyIntegrationTests.
import Foundation

/// Namespace for fixture lookup. Not a service locator: it reads one
/// immutable, caller-explicit directory (env `CLIPY_FIXTURES_DIR`); it holds
/// no mutable state and no History functionality.
enum FixtureCatalog {
    /// The fixture tree is missing or malformed (no manifest).
    enum Error: Swift.Error {
        case missingTree
    }

    /// The unpacked fixture root: `$CLIPY_FIXTURES_DIR` when it contains
    /// `manifest.json`, else nil.
    static let root: URL? = {
        guard let path = ProcessInfo.processInfo.environment["CLIPY_FIXTURES_DIR"],
              FileManager.default.fileExists(atPath: path + "/manifest.json") else {
            return nil
        }
        return URL(fileURLWithPath: path, isDirectory: true)
    }()

    /// True when the fixture tree is present; the suite-gating trait reads
    /// this (`.enabled(if: FixtureCatalog.available)`).
    static var available: Bool { root != nil }

    /// The URL of one fixture file, or `Error.missingTree` when the tree is
    /// absent (unreachable in practice behind the availability gate, but a
    /// thrown error beats a trap).
    static func url(_ relativePath: String) throws -> URL {
        guard let root else { throw Error.missingTree }
        return root.appendingPathComponent(relativePath)
    }

    /// One fixture file's bytes.
    static func data(_ relativePath: String) throws -> Data {
        try Data(contentsOf: url(relativePath))
    }

    /// One fixture file decoded as UTF-8 text.
    static func text(_ relativePath: String) throws -> String {
        try String(contentsOf: url(relativePath), encoding: .utf8)
    }
}
