/// PasteboardMarkers — the fixed pasteboard concealment/private-marker set
/// recognized at the capture seam. Owning spec: docs/05-authority-kernel.md
/// §6.1 (capture preparation step 3) and docs/02-domain.md §2.1 (normalized
/// representation set); roadmap: docs/roadmap/04-pasteboardadapter.md.
///
/// A marker is a property of the pasteboard item, not a payload
/// representation: when any one of these types is present, the whole
/// capture is concealed (`ClipboardCapture.isConcealed`) and HistoryStorage
/// rejects the entire observation as `.invalidInput(.excludedFromHistory)`
/// before fingerprinting (docs/05-authority-kernel.md §6.1 step 1). The
/// adapter never strips a marker and submits its sibling plaintext as an
/// ordinary capture (docs/roadmap/04-pasteboardadapter.md deliverable 1).
///
/// The set mirrors `IngestPreparationActor.standardTransientTypeIdentifiers`
/// exactly (defense in depth: storage re-checks the same six strings).
import Foundation

/// The six recognized concealment/private marker type identifiers.
///
/// V1 uses six third-party convention strings as a best-effort denylist for
/// private/transient clipboard content. None of these raw identifiers is a
/// framework-owned guarantee that sensitive content cannot reach History;
/// marker detection is one defense-in-depth signal at the capture seam:
///
/// - `org.nspasteboard.ConcealedType` / `org.nspasteboard.TransientType` /
///   `org.nspasteboard.AutoGeneratedType` — the nspasteboard.org conventions.
/// - `de.petermaurer.TransientPasteboardType` — the transient-pasteboard
///   convention used by several password managers.
/// - `com.agilebits.onepassword` / `com.typeit4me.clipping` — established
///   application conventions for private clipboard content.
enum PasteboardMarkers {
    /// The whole-capture exclusion set (docs/05-authority-kernel.md §6.1).
    ///
    /// Deliberately a set of raw strings, not `NSPasteboard.PasteboardType`,
    /// so the check is testable against pure type-identifier lists.
    static let concealedTypeIdentifiers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
    ]

    /// Whether a pasteboard item carrying exactly `types` must be excluded
    /// from History as concealed/private/transient content. Any single
    /// marker excludes the whole item (whole-capture semantics,
    /// docs/05-authority-kernel.md §6.1 step 3).
    static func marksConcealed(_ types: [String]) -> Bool {
        types.contains { concealedTypeIdentifiers.contains($0) }
    }
}
