/// PasteboardAdapter acceptance gates (docs/roadmap/04-pasteboardadapter.md
/// "Acceptance"):
///
/// - Capture freezes all retainable typed representations of the pasteboard
///   item (03a §4; 01 §5.1).
/// - Multiple pasteboard items preserve their order, duplicate types on
///   different items, and byte-exact payloads through capture and paste.
/// - A sibling `org.nspasteboard.ConcealedType` — and every other marker in
///   the configured private/transient set — short-circuits the WHOLE item
///   before any payload accessor runs; the explicit concealed outcome has
///   no retainable bytes for a caller to submit.
/// - `write(_:)` stages the payload's Effective Content representations and
///   lineage hint on one new item before touching the pasteboard, then makes
///   one framework write attempt; the hint decodes back into
///   `CopyOriginObservation.lineageHint` on the next capture (03b §9; 04
///   §8; 01 §5.6). End-to-end coalescing via the hint is proven by WS4
///   through History, not here.
/// - The observer captures the current contents immediately on start, then
///   fires the handler once per distinct `changeCount` bump.
/// - A start/end `changeCount` mismatch discards every representation read
///   during that attempt and produces an explicit content-free retry outcome;
///   the complete-capture convenience returns nil (REVIEW Card 5B).
/// - Failure is explicit, never silent (audit SPEC-IMPL-005,
///   docs/reviews/2026-08-20-clipy-maccy-audit/02-spec-implementation.md):
///   a declared-but-unavailable type is recorded by the
///   `CaptureOutcome.declaredUnavailable` case instead of being silently
///   dropped, and `write(_:)` throws
///   `PasteboardWriteFailure` for refused item staging or a refused whole-item
///   write instead of ignoring framework Booleans. A Debug-only package,
///   immutable failure configuration injects unavailable reads, staging
///   rejection, and completed-item rejection; it is absent from Release and
///   unavailable to ordinary adapter clients (REVIEW Card 5D).
///
/// Every test uses a private `NSPasteboard(name:)` with a unique name, so
/// the suite never reads or mutates the user's clipboard.
import AppKit
import Foundation
import HistoryCore
import Testing
@testable import PasteboardAdapter

// MARK: - Fixtures

/// The six exact marker strings, pinned literally so any drift in
/// `PasteboardMarkers.concealedTypeIdentifiers` fails here (they mirror
/// `IngestPreparationActor.standardTransientTypeIdentifiers`).
private let concealmentMarkers: [String] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "de.petermaurer.TransientPasteboardType",
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
]

/// A fresh, uniquely named private pasteboard per test.
@MainActor
private func makePasteboard() -> NSPasteboard {
    NSPasteboard(
        name: NSPasteboard.Name("com.clipy.pasteboardadaptertests." + UUID().uuidString)
    )
}

/// Spins the main run loop in short slices until `condition` holds or
/// `timeout` elapses, servicing the observer's main-RunLoop `Timer` (whose
/// block polls synchronously on the main actor) while the synchronous test
/// body waits. Returns whether the condition was met.
@MainActor
private func spinMainRunLoop(until condition: () -> Bool, timeout: TimeInterval = 2) -> Bool {
    let deadline = Date().addingTimeInterval(timeout)
    while Date() < deadline {
        if condition() { return true }
        _ = RunLoop.main.run(mode: .default, before: Date(timeIntervalSinceNow: 0.02))
    }
    return condition()
}

// MARK: - Capture freeze (03a §4; roadmap 04 acceptance 1)

@Test @MainActor
func captureFreezesEveryRetainableTypedRepresentation() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    pasteboard.setData(Data("<b>rich</b>".utf8), forType: NSPasteboard.PasteboardType("public.html"))

    let observedAt = Date(timeIntervalSince1970: 1_000_000)
    let capture = PasteboardAdapter(pasteboard: pasteboard).capture(observedAt: observedAt)

    #expect(capture != nil)
    #expect(capture?.observedAt == observedAt)
    #expect(capture?.isConcealed == false)
    #expect(capture?.origin.lineageHint == nil)
    #expect(capture?.representations.count == 2)
    #expect(
        capture?.representations.contains {
            $0.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue
                && $0.bytes == Data("plain".utf8)
        } == true
    )
    #expect(
        capture?.representations.contains {
            $0.typeIdentifier == "public.html" && $0.bytes == Data("<b>rich</b>".utf8)
        } == true
    )
}

/// DATA-9a characterization: the owning spec has not approved any browser or
/// editor bookkeeping UTI as ignorable for dedup. This synthetic unknown type
/// therefore remains ordinary content at the adapter seam. The fixture proves
/// the present ceiling only: it does not identify a real application's UTI or
/// authorize adding this identifier to an ignore list.
@Test @MainActor
func volatileBookkeepingBytesRemainPartOfTheCaptureInput() throws {
    let textBytes = Data("same user-visible text".utf8)
    let bookkeepingType = NSPasteboard.PasteboardType(
        "com.clipy.tests.synthetic-bookkeeping-token"
    )
    let firstBookkeepingBytes = Data("generation-1".utf8)
    let secondBookkeepingBytes = Data("generation-2".utf8)
    let observedAt = Date(timeIntervalSince1970: 1_000_000)

    let firstPasteboard = makePasteboard()
    firstPasteboard.clearContents()
    let firstItem = NSPasteboardItem()
    #expect(firstItem.setData(textBytes, forType: .string))
    #expect(firstItem.setData(firstBookkeepingBytes, forType: bookkeepingType))
    #expect(firstPasteboard.writeObjects([firstItem]))

    let secondPasteboard = makePasteboard()
    secondPasteboard.clearContents()
    let secondItem = NSPasteboardItem()
    #expect(secondItem.setData(textBytes, forType: .string))
    #expect(secondItem.setData(secondBookkeepingBytes, forType: bookkeepingType))
    #expect(secondPasteboard.writeObjects([secondItem]))

    let firstCapture = try #require(
        PasteboardAdapter(pasteboard: firstPasteboard).capture(observedAt: observedAt)
    )
    let secondCapture = try #require(
        PasteboardAdapter(pasteboard: secondPasteboard).capture(observedAt: observedAt)
    )
    let firstByType = Dictionary(
        uniqueKeysWithValues: firstCapture.representations.map {
            ($0.typeIdentifier, $0.bytes)
        }
    )
    let secondByType = Dictionary(
        uniqueKeysWithValues: secondCapture.representations.map {
            ($0.typeIdentifier, $0.bytes)
        }
    )

    #expect(firstByType[NSPasteboard.PasteboardType.string.rawValue] == textBytes)
    #expect(secondByType[NSPasteboard.PasteboardType.string.rawValue] == textBytes)
    #expect(firstByType[bookkeepingType.rawValue] == firstBookkeepingBytes)
    #expect(secondByType[bookkeepingType.rawValue] == secondBookkeepingBytes)
    #expect(firstCapture.representations != secondCapture.representations)

    // History currently receives every non-marker representation as Canonical
    // input. Until DATA-9b names and specifies a representation role, these
    // two captures are intentionally distinguishable rather than coalesced on
    // user-visible text alone.
}

#if DEBUG
@Test @MainActor
func pasteboardChangeBetweenRepresentationReadsProducesContentFreeRetryOutcome() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("old plain".utf8), forType: .string)
    pasteboard.setData(
        Data("<b>old rich</b>".utf8),
        forType: NSPasteboard.PasteboardType("public.html")
    )
    let startChangeCount = pasteboard.changeCount
    var didReplaceContents = false
    var payloadReads = 0
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadCompletionHook = { _ in
        payloadReads += 1
        guard !didReplaceContents else { return }
        didReplaceContents = true
        pasteboard.clearContents()
        pasteboard.setData(Data("new plain".utf8), forType: .string)
        pasteboard.setData(
            Data("<b>new rich</b>".utf8),
            forType: NSPasteboard.PasteboardType("public.html")
        )
    }

    let outcome = try #require(adapter.captureOutcome())

    #expect(didReplaceContents)
    // The second old representation cannot contribute to a complete freeze.
    // Do not invoke its accessor after the first read changed ownership.
    #expect(payloadReads == 1)
    guard case let .changedDuringRead(changed) = outcome else {
        Issue.record("expected a content-free changed-during-read outcome")
        return
    }
    #expect(changed.startChangeCount == startChangeCount)
    #expect(changed.endChangeCount == pasteboard.changeCount)
    #expect(changed.endChangeCount != changed.startChangeCount)
    // Neither the old first read nor the new board may enter History as a
    // complete snapshot. Ownership change is its own retry reason, not an
    // unavailable-type diagnosis.
}

@Test @MainActor
func completeCaptureConvenienceRejectsPasteboardChangedDuringRead() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("old plain".utf8), forType: .string)
    pasteboard.setData(
        Data("<b>old rich</b>".utf8),
        forType: NSPasteboard.PasteboardType("public.html")
    )
    var didReplaceContents = false
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadCompletionHook = { _ in
        guard !didReplaceContents else { return }
        didReplaceContents = true
        pasteboard.clearContents()
        pasteboard.setString("new plain", forType: .string)
    }

    #expect(adapter.capture() == nil)
    #expect(didReplaceContents)
}
#endif

@Test @MainActor
func captureOfEmptyPasteboardReturnsNil() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()

    #expect(PasteboardAdapter(pasteboard: pasteboard).capture() == nil)
}

@Test @MainActor
func multipleItemsPreserveOrderRepeatedTypesAndExactBytesThroughPaste() throws {
    let pasteboard = makePasteboard()
    let first = NSPasteboardItem()
    let second = NSPasteboardItem()
    let custom = NSPasteboard.PasteboardType("com.clipy.tests.opaque")
    let firstText = Data("first\u{0}\n".utf8)
    let secondText = Data("second\u{301}".utf8)
    let firstOpaque = Data([0x00, 0xFF, 0x81])
    let secondOpaque = Data([0xFF, 0x00, 0x82])
    #expect(first.setData(firstText, forType: .string))
    #expect(first.setData(firstOpaque, forType: custom))
    #expect(second.setData(secondText, forType: .string))
    #expect(second.setData(secondOpaque, forType: custom))
    #expect(pasteboard.writeObjects([first, second]))
    let adapter = PasteboardAdapter(pasteboard: pasteboard)
    let capture = try #require(adapter.capture())
    #expect(capture.representations.count == 4)
    #expect(capture.representations.map(\.pasteboardItemIndex) == [0, 0, 1, 1])
    let id = HistoryItemID(rawValue: UUID())
    try adapter.write(PastePayload(
        item: HistoryItemReference(id: id, contentVersion: .initial),
        representations: capture.representations.reversed().map {
            HistoryRepresentation(typeIdentifier: $0.typeIdentifier, bytes: $0.bytes,
                pasteboardItemIndex: $0.pasteboardItemIndex)
        }, lineageHint: id
    ))
    let written = try #require(pasteboard.pasteboardItems)
    #expect(written.count == 2)
    #expect(written[0].data(forType: .string) == firstText)
    #expect(written[1].data(forType: .string) == secondText)
    #expect(written[0].data(forType: custom) == firstOpaque)
    #expect(written[1].data(forType: custom) == secondOpaque)
    let recaptured = try #require(adapter.capture())
    #expect(recaptured.origin.lineageHint == id)
    #expect(Set(recaptured.representations) == Set(capture.representations))
}

@Test @MainActor
func multiItemLineageRequiresTheSameValidHintOnEveryItem() throws {
    let id = HistoryItemID(rawValue: UUID())
    for secondHint in [Optional<Data>.none, Data("invalid".utf8), PasteboardLineageHint.encode(HistoryItemID(rawValue: UUID()))] {
        let pasteboard = makePasteboard()
        let first = NSPasteboardItem()
        let second = NSPasteboardItem()
        #expect(first.setString("one", forType: .string))
        #expect(second.setString("two", forType: .string))
        let hintType = NSPasteboard.PasteboardType(PasteboardLineageHint.typeIdentifier)
        #expect(first.setData(PasteboardLineageHint.encode(id), forType: hintType))
        if let secondHint { #expect(second.setData(secondHint, forType: hintType)) }
        #expect(pasteboard.writeObjects([first, second]))
        let capture = try #require(PasteboardAdapter(pasteboard: pasteboard).capture())
        #expect(capture.origin.lineageHint == nil)
        #expect(capture.representations.count == 2)
    }
}

@Test @MainActor
func multiItemEmptyConstituentIsNotSilentlyDropped() throws {
    let pasteboard = makePasteboard()
    let first = NSPasteboardItem()
    let second = NSPasteboardItem()
    #expect(first.setString("one", forType: .string))
    #expect(second.setData(Data(), forType: .string))
    #expect(pasteboard.writeObjects([first, second]))
    let adapter = PasteboardAdapter(pasteboard: pasteboard)
    guard case .unsupportedMultiItem(let unsupported) = adapter.captureOutcome() else {
        Issue.record("An empty constituent item must not disappear from a complete capture")
        return
    }
    #expect(unsupported.itemCount == 2)
    #expect(adapter.capture() == nil)
}

#if DEBUG
@Test(arguments: concealmentMarkers) @MainActor
func privacyMarkerOnLaterItemRejectsWholeGestureBeforePayloadRead(marker: String) throws {
    let pasteboard = makePasteboard()
    let first = NSPasteboardItem()
    let second = NSPasteboardItem()
    #expect(first.setString("private sibling", forType: .string))
    #expect(second.setString("private", forType: .string))
    #expect(second.setData(Data([1]), forType: NSPasteboard.PasteboardType(marker)))
    #expect(pasteboard.writeObjects([first, second]))
    var payloadAccessorCalls: [String] = []
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadObserver = { payloadAccessorCalls.append($0) }
    guard case .concealed(let concealed) = adapter.captureOutcome() else {
        Issue.record("A marker on any item must exclude the complete capture")
        return
    }
    #expect(concealed.markerTypeIdentifier == marker)
    #expect(payloadAccessorCalls.isEmpty)
}
#endif

#if DEBUG
@Test @MainActor
func laterItemStagingFailurePreservesTheExistingPasteboard() throws {
    let pasteboard = makePasteboard()
    #expect(pasteboard.setString("keep prior clipboard", forType: .string))
    let oldChangeCount = pasteboard.changeCount
    let rejectedType = "com.clipy.tests.rejected-later-item"
    let adapter = PasteboardAdapter(pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(rejectedWriteTypeIdentifiers: [rejectedType]))
    let id = HistoryItemID(rawValue: UUID())
    let payload = PastePayload(
        item: HistoryItemReference(id: id, contentVersion: .initial),
        representations: [
            HistoryRepresentation(typeIdentifier: "public.utf8-plain-text", bytes: Data("first".utf8)),
            HistoryRepresentation(typeIdentifier: rejectedType, bytes: Data([1]), pasteboardItemIndex: 1)
        ], lineageHint: id
    )
    #expect(throws: PasteboardWriteFailure.representationsRejected(typeIdentifiers: [rejectedType])) {
        try adapter.write(payload)
    }
    #expect(pasteboard.changeCount == oldChangeCount)
    #expect(pasteboard.string(forType: .string) == "keep prior clipboard")
}
#endif

// MARK: - Concealment markers (roadmap 04 acceptance 2)

#if DEBUG
@Test @MainActor
func declaredConcealmentMarkerShortCircuitsBeforeReadingLargeSiblingPayload() throws {
    let marker = "org.nspasteboard.ConcealedType"
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(
        Data(repeating: 0x73, count: 5 * 1_024 * 1_024),
        forType: .string
    )
    pasteboard.setData(
        Data("marker".utf8),
        forType: NSPasteboard.PasteboardType(marker)
    )
    var payloadAccessorCalls: [String] = []
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadObserver = { typeIdentifier in
        payloadAccessorCalls.append(typeIdentifier)
    }

    let outcome = try #require(adapter.captureOutcome())

    #expect(payloadAccessorCalls.isEmpty)
    guard case let .concealed(concealed) = outcome else {
        Issue.record("expected the concealed-before-bytes outcome")
        return
    }
    #expect(concealed.markerTypeIdentifier == marker)
    #expect(concealed.changeCount == pasteboard.changeCount)
    #expect(adapter.capture() == nil)
    #expect(payloadAccessorCalls.isEmpty)
}

@Test @MainActor
func payloadReadInstrumentationObservesUnmarkedCaptureWithoutChangingIt() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("ordinary".utf8), forType: .string)
    var payloadAccessorCalls: [String] = []
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadObserver = { typeIdentifier in
        payloadAccessorCalls.append(typeIdentifier)
    }

    let outcome = try #require(adapter.captureOutcome())

    #expect(payloadAccessorCalls == [NSPasteboard.PasteboardType.string.rawValue])
    guard case let .complete(complete) = outcome else {
        Issue.record("expected the stable complete outcome")
        return
    }
    #expect(complete.changeCount == pasteboard.changeCount)
    #expect(complete.capture.isConcealed == false)
    #expect(complete.capture.representations == [
        CapturedRepresentation(
            typeIdentifier: NSPasteboard.PasteboardType.string.rawValue,
            bytes: Data("ordinary".utf8)
        )
    ])
}
#endif

@Test @MainActor
func everyConcealmentMarkerMarksTheWholeCaptureConcealed() {
    for marker in concealmentMarkers {
        let pasteboard = makePasteboard()
        pasteboard.clearContents()
        pasteboard.setData(Data("sensitive".utf8), forType: .string)
        pasteboard.setData(Data("marker".utf8), forType: NSPasteboard.PasteboardType(marker))

        guard let outcome = PasteboardAdapter(pasteboard: pasteboard).captureOutcome() else {
            Issue.record("expected concealed outcome for \(marker)")
            continue
        }

        guard case let .concealed(concealed) = outcome else {
            Issue.record("expected concealed outcome for \(marker)")
            continue
        }
        #expect(concealed.markerTypeIdentifier == marker, "\(marker)")
        #expect(concealed.changeCount == pasteboard.changeCount, "\(marker)")
        // Whole-item privacy semantics: declared types are enough to reject
        // this observation. The case has no capture field, so sibling bytes
        // cannot be retained or accidentally submitted by a caller.
    }
}

@Test @MainActor
func marksConcealedRecognizesExactlyTheMarkerSet() {
    for marker in concealmentMarkers {
        #expect(PasteboardMarkers.marksConcealed([marker]), "\(marker)")
        #expect(
            PasteboardMarkers.marksConcealed(["public.utf8-plain-text", marker]),
            "\(marker)"
        )
    }
    #expect(!PasteboardMarkers.marksConcealed(["public.utf8-plain-text", "public.html"]))
    #expect(!PasteboardMarkers.marksConcealed([]))
    #expect(PasteboardMarkers.concealedTypeIdentifiers.count == 6)
    #expect(concealmentMarkers.allSatisfy { PasteboardMarkers.concealedTypeIdentifiers.contains($0) })
}

// MARK: - Lineage hint codec (03b §9; roadmap 04 acceptance 3, codec half)

@Test @MainActor
func lineageHintCodecRoundTripsAndRejectsMalformedData() {
    #expect(PasteboardLineageHint.typeIdentifier == "com.clipy.lineageHint")

    let id = HistoryItemID(rawValue: UUID())
    #expect(PasteboardLineageHint.encode(id) == Data(id.rawValue.uuidString.utf8))
    #expect(PasteboardLineageHint.decode(PasteboardLineageHint.encode(id)) == id)

    #expect(PasteboardLineageHint.decode(Data()) == nil)
    #expect(PasteboardLineageHint.decode(Data("not-a-uuid".utf8)) == nil)
    #expect(
        PasteboardLineageHint.decode(Data("AB108DC6-779D-4C78-B7F5-45BE50EF1CD8".utf8)) != nil
    )
}

// MARK: - Paste write + hint round-trip (03b §9; 04 §8; roadmap 04 acceptance 3)

@Test @MainActor
func writeRoundTripsLineageHintIntoCaptureOrigin() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    let adapter = PasteboardAdapter(pasteboard: pasteboard)

    let id = HistoryItemID(rawValue: UUID())
    let payload = PastePayload(
        item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
        representations: [
            HistoryRepresentation(typeIdentifier: "public.utf8-plain-text", bytes: Data("Clipy".utf8)),
            HistoryRepresentation(typeIdentifier: "public.html", bytes: Data("<b>Clipy</b>".utf8)),
        ],
        lineageHint: id
    )

    try adapter.write(payload)

    let capture = adapter.capture()
    #expect(capture != nil)
    #expect(capture?.origin.lineageHint == id)
    #expect(capture?.isConcealed == false)
    // The hint marker is metadata: it must not survive as a retained
    // representation of the re-captured paste.
    #expect(capture?.representations.count == 2)
    #expect(
        capture?.representations.contains {
            $0.typeIdentifier == PasteboardLineageHint.typeIdentifier
        } == false
    )
}

@Test @MainActor
func writeReplacesPriorContentWithOneCompleteItem() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("stale".utf8), forType: NSPasteboard.PasteboardType("com.clipy.tests.stale"))
    let adapter = PasteboardAdapter(pasteboard: pasteboard)

    let id = HistoryItemID(rawValue: UUID())
    try adapter.write(
        PastePayload(
            item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
            representations: [
                HistoryRepresentation(
                    typeIdentifier: "public.utf8-plain-text",
                    bytes: Data("fresh".utf8)
                ),
                HistoryRepresentation(
                    typeIdentifier: "public.html",
                    bytes: Data("<b>fresh</b>".utf8)
                )
            ],
            lineageHint: id
        )
    )

    #expect(pasteboard.pasteboardItems?.count == 1)
    let item = pasteboard.pasteboardItems?.first
    let typeIdentifiers = item?.types.map { $0.rawValue } ?? []
    #expect(typeIdentifiers.contains("public.utf8-plain-text"))
    #expect(typeIdentifiers.contains("public.html"))
    #expect(typeIdentifiers.contains(PasteboardLineageHint.typeIdentifier))
    #expect(!typeIdentifiers.contains("com.clipy.tests.stale"))
    #expect(item?.data(forType: .string) == Data("fresh".utf8))
    #expect(
        item?.data(forType: NSPasteboard.PasteboardType("public.html"))
            == Data("<b>fresh</b>".utf8)
    )
    #expect(
        item?.data(forType: NSPasteboard.PasteboardType(PasteboardLineageHint.typeIdentifier))
            == PasteboardLineageHint.encode(id)
    )
}

// MARK: - Partial-freeze record + typed write failure (audit SPEC-IMPL-005)

#if DEBUG
@Test @MainActor
func captureRecordsADeclaredButUnavailableTypeAsAPartialFreeze() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    pasteboard.setData(Data("<b>rich</b>".utf8), forType: NSPasteboard.PasteboardType("public.html"))
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            unavailableTypeIdentifiers: ["public.html"]
        )
    )

    guard let outcome = adapter.captureOutcome() else {
        Issue.record("expected the declared-unavailable partial outcome")
        return
    }

    // The nil-data type is RECORDED, never silently dropped. The available
    // representation is still frozen, and the closed case marks it partial
    // without claiming why the system did not vend those bytes.
    guard case let .declaredUnavailable(partial) = outcome else {
        Issue.record("expected the declared-unavailable partial outcome")
        return
    }
    #expect(partial.unavailableTypeIdentifiers == ["public.html"])
    #expect(partial.changeCount == pasteboard.changeCount)
    #expect(partial.partialCapture.representations.count == 1)
    #expect(
        partial.partialCapture.representations.first?.typeIdentifier
            == NSPasteboard.PasteboardType.string.rawValue
    )
    #expect(
        partial.partialCapture.representations.first?.bytes == Data("plain".utf8)
    )
    #expect(adapter.capture() == nil)
}
#endif

@Test @MainActor
func captureOfAFullyObservedItemIsACompleteOutcome() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    let stableChangeCount = pasteboard.changeCount

    let observedAt = Date(timeIntervalSince1970: 1_760_000_000)
    guard let outcome = PasteboardAdapter(pasteboard: pasteboard)
        .captureOutcome(observedAt: observedAt) else {
        Issue.record("expected the stable complete outcome")
        return
    }

    guard case let .complete(complete) = outcome else {
        Issue.record("expected the stable complete outcome")
        return
    }
    #expect(complete.changeCount == stableChangeCount)
    // The convenience half drops the record but freezes the same bytes;
    // both calls share one injected observedAt so the comparison is
    // deterministic (the default Date() stamps would differ sub-second).
    #expect(
        PasteboardAdapter(pasteboard: pasteboard)
            .capture(observedAt: observedAt) == complete.capture
    )
}

#if DEBUG
@Test @MainActor
func everyUnavailableRepresentationProducesAnExplicitPartialOutcome() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            unavailableTypeIdentifiers: [
                NSPasteboard.PasteboardType.string.rawValue
            ]
        )
    )

    guard let outcome = adapter.captureOutcome() else {
        Issue.record("expected the all-unavailable partial outcome")
        return
    }

    // The observer has consumed this changeCount, so an all-unavailable
    // gesture must remain distinguishable from a cleared pasteboard.
    guard case let .declaredUnavailable(partial) = outcome else {
        Issue.record("expected the all-unavailable partial outcome")
        return
    }
    #expect(
        partial.unavailableTypeIdentifiers
            == [NSPasteboard.PasteboardType.string.rawValue]
    )
    #expect(partial.partialCapture.representations.isEmpty)
    #expect(partial.changeCount == pasteboard.changeCount)
    #expect(adapter.capture() == nil)
}

@Test @MainActor
func rejectedRepresentationStagingLeavesExistingPasteboardUntouched() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    let sentinelType = NSPasteboard.PasteboardType("com.clipy.tests.sentinel")
    let sentinelBytes = Data("keep me".utf8)
    pasteboard.setData(sentinelBytes, forType: sentinelType)
    let sentinelChangeCount = pasteboard.changeCount
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            rejectedWriteTypeIdentifiers: ["public.html"]
        )
    )

    let id = HistoryItemID(rawValue: UUID())
    let payload = PastePayload(
        item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
        representations: [
            HistoryRepresentation(typeIdentifier: "public.utf8-plain-text", bytes: Data("Clipy".utf8)),
            HistoryRepresentation(typeIdentifier: "public.html", bytes: Data("<b>Clipy</b>".utf8)),
        ],
        lineageHint: id
    )

    // The typed failure names every refused staged type identifier.
    do {
        try adapter.write(payload)
        Issue.record("SPEC-IMPL-005: expected PasteboardWriteFailure")
    } catch let failure as PasteboardWriteFailure {
        #expect(
            failure == .representationsRejected(typeIdentifiers: ["public.html"]),
            "SPEC-IMPL-005: the failure names the refused representation"
        )
    }

    // All setters target an unbound in-memory item. A staging failure is
    // reported before clear/writeObjects, so even changeCount is unchanged.
    #expect(pasteboard.changeCount == sentinelChangeCount)
    #expect(pasteboard.pasteboardItems?.count == 1)
    let item = pasteboard.pasteboardItems?.first
    #expect(item?.types.map(\.rawValue) == [sentinelType.rawValue])
    #expect(item?.data(forType: sentinelType) == sentinelBytes)
    #expect(item?.data(forType: .string) == nil)
    #expect(item?.data(forType: NSPasteboard.PasteboardType("public.html")) == nil)
    #expect(
        item?.data(forType: NSPasteboard.PasteboardType(PasteboardLineageHint.typeIdentifier))
            == nil
    )
}

@Test @MainActor
func rejectedLineageHintStagingLeavesExistingPasteboardUntouched() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    let sentinelType = NSPasteboard.PasteboardType("com.clipy.tests.sentinel")
    let sentinelBytes = Data("keep me too".utf8)
    pasteboard.setData(sentinelBytes, forType: sentinelType)
    let sentinelChangeCount = pasteboard.changeCount
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            rejectedWriteTypeIdentifiers: [
                PasteboardLineageHint.typeIdentifier
            ]
        )
    )

    let id = HistoryItemID(rawValue: UUID())
    let payload = PastePayload(
        item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
        representations: [
            HistoryRepresentation(
                typeIdentifier: "public.utf8-plain-text",
                bytes: Data("Clipy".utf8)
            )
        ],
        lineageHint: id
    )

    do {
        try adapter.write(payload)
        Issue.record("SPEC-IMPL-005: expected PasteboardWriteFailure")
    } catch let failure as PasteboardWriteFailure {
        #expect(
            failure == .representationsRejected(
                typeIdentifiers: [PasteboardLineageHint.typeIdentifier]
            ),
            "SPEC-IMPL-005: a hint refusal is named like any other type"
        )
    }

    #expect(pasteboard.changeCount == sentinelChangeCount)
    #expect(pasteboard.pasteboardItems?.count == 1)
    let item = pasteboard.pasteboardItems?.first
    #expect(item?.types.map(\.rawValue) == [sentinelType.rawValue])
    #expect(item?.data(forType: sentinelType) == sentinelBytes)
    #expect(item?.data(forType: .string) == nil)
    #expect(
        item?.data(forType: NSPasteboard.PasteboardType(PasteboardLineageHint.typeIdentifier))
            == nil
    )
}

@Test @MainActor
func rejectedWholeItemIsReportedAfterClearingThePasteboard() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    let sentinelType = NSPasteboard.PasteboardType("com.clipy.tests.sentinel")
    pasteboard.setData(Data("not retained".utf8), forType: sentinelType)
    let sentinelChangeCount = pasteboard.changeCount
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            rejectCompletedItem: true
        )
    )

    let id = HistoryItemID(rawValue: UUID())
    let payload = PastePayload(
        item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
        representations: [
            HistoryRepresentation(
                typeIdentifier: "public.utf8-plain-text",
                bytes: Data("Clipy".utf8)
            )
        ],
        lineageHint: id
    )

    do {
        try adapter.write(payload)
        Issue.record("SPEC-IMPL-005: expected whole-item write rejection")
    } catch let failure as PasteboardWriteFailure {
        #expect(failure == .itemRejected)
    }

    // Whole-item refusal happens after clearContents(). There is no rollback
    // contract: this deterministic fixture has advanced and is now empty.
    #expect(pasteboard.changeCount > sentinelChangeCount)
    #expect((pasteboard.pasteboardItems ?? []).isEmpty)
}
#endif

#if DEBUG
@Test @MainActor
func observerDeliversAPartialOutcomeForTheCompositionToJudge() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    pasteboard.setData(Data("<b>rich</b>".utf8), forType: NSPasteboard.PasteboardType("public.html"))
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            unavailableTypeIdentifiers: ["public.html"]
        )
    )
    let observer = PasteboardObserver(adapter: adapter, pollInterval: 0.05)

    var received: [CaptureOutcome] = []
    observer.start { outcome in
        received.append(outcome)
    }
    defer { observer.stop() }

    // start delivers the CURRENT contents synchronously: the partial
    // freeze reaches the handler owner (the composition root drops it
    // rather than admitting partial Canonical Content, 01 §5.1).
    #expect(received.count == 1)
    guard let firstOutcome = received.first else {
        Issue.record("expected the observer to deliver an outcome")
        return
    }
    guard case let .declaredUnavailable(partial) = firstOutcome else {
        Issue.record("expected the observer to deliver the partial outcome")
        return
    }
    #expect(partial.unavailableTypeIdentifiers == ["public.html"])
    #expect(partial.partialCapture.representations.count == 1)
}
#endif

// MARK: - Observation (01 §5.1; roadmap 04 deliverable 3, acceptance 4)

@Test @MainActor
func observerCapturesImmediatelyThenFiresOncePerChangeCountBump() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setString("first", forType: .string)
    let observer = PasteboardObserver(
        adapter: PasteboardAdapter(pasteboard: pasteboard),
        pollInterval: 0.05
    )

    var received: [ClipboardCapture] = []
    observer.start { outcome in
        if case let .complete(complete) = outcome {
            received.append(complete.capture)
        }
    }

    // start delivers the CURRENT contents synchronously before returning.
    #expect(received.count == 1)
    #expect(
        received.first?.representations.contains {
            $0.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue
                && $0.bytes == Data("first".utf8)
        } == true
    )

    // A real change (clear + write bumps the change count) is delivered
    // once, with the new contents.
    pasteboard.clearContents()
    pasteboard.setString("second", forType: .string)
    #expect(spinMainRunLoop { received.count >= 2 })
    #expect(
        received.last?.representations.contains {
            $0.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue
                && $0.bytes == Data("second".utf8)
        } == true
    )

    // A change that leaves nothing retainable is recorded but not
    // delivered: the handler fires only for non-nil captures.
    pasteboard.clearContents()
    let deliveredEmptyChange = spinMainRunLoop(until: { received.count >= 3 }, timeout: 0.4)
    #expect(!deliveredEmptyChange)

    observer.stop()
}

@Test @MainActor
func observerCanBaselineCurrentGenerationBeforePollingLaterCopies() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setString("copied-while-paused", forType: .string)
    let observer = PasteboardObserver(
        adapter: PasteboardAdapter(pasteboard: pasteboard),
        pollInterval: 0.05
    )

    var received: [ClipboardCapture] = []
    observer.start(captureCurrent: false) { outcome in
        if case let .complete(complete) = outcome {
            received.append(complete.capture)
        }
    }
    defer { observer.stop() }

    #expect(received.isEmpty)
    pasteboard.clearContents()
    pasteboard.setString("copied-after-resume", forType: .string)
    #expect(spinMainRunLoop { received.count == 1 })
    #expect(
        received[0].representations.contains {
            $0.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue
                && $0.bytes == Data("copied-after-resume".utf8)
        }
    )
}

@Test @MainActor
func observerStopHaltsDelivery() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setString("first", forType: .string)
    let observer = PasteboardObserver(
        adapter: PasteboardAdapter(pasteboard: pasteboard),
        pollInterval: 0.05
    )

    var received: [ClipboardCapture] = []
    observer.start { outcome in
        if case let .complete(complete) = outcome {
            received.append(complete.capture)
        }
    }
    observer.stop()

    pasteboard.clearContents()
    pasteboard.setString("after-stop", forType: .string)
    let deliveredAfterStop = spinMainRunLoop(until: { received.count >= 2 }, timeout: 0.4)
    #expect(!deliveredAfterStop)
    #expect(received.count == 1)
}

#if DEBUG
/// Real named-pasteboard limits, serialized so the two native large-payload
/// cases do not overlap their provider allocations with one another.
@Suite(.serialized) @MainActor
struct CaptureResourceLimitTests {
    @Test(arguments: [false, true])
    func excessiveDeclaredFormatsOrItemsStopBeforePayloadReads(tooManyItems: Bool) throws {
        let pasteboard = makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let count = HistoryLimits.standard.maximumRepresentationsPerCaptureOrRevision + 1
        var items: [NSPasteboardItem] = []
        if tooManyItems {
            for _ in 0..<count {
                let item = NSPasteboardItem()
                #expect(item.setData(Data([1]), forType: .string))
                items.append(item)
            }
        } else {
            let item = NSPasteboardItem()
            for index in 0..<count {
                #expect(item.setData(Data([1]), forType: .init("com.clipy.tests.limit.\(index)")))
            }
            items.append(item)
        }
        #expect(pasteboard.writeObjects(items))
        var reads = 0
        var adapter = PasteboardAdapter(pasteboard: pasteboard)
        adapter.payloadReadObserver = { _ in reads += 1 }
        guard case .unsupportedMultiItem(let rejected) = adapter.captureOutcome() else {
            Issue.record("Over-limit declarations must produce a content-free rejection")
            return
        }
        #expect(rejected.itemCount == items.count)
        #expect(rejected.changeCount == pasteboard.changeCount)
        #expect(reads == 0)
    }

    @Test func privacyOnLastItemTakesPrecedenceOverTheDeclarationLimit() throws {
        let pasteboard = makePasteboard()
        defer { pasteboard.releaseGlobally() }
        var items: [NSPasteboardItem] = []
        for _ in 0...HistoryLimits.standard.maximumRepresentationsPerCaptureOrRevision {
            let item = NSPasteboardItem()
            #expect(item.setData(Data([1]), forType: .string))
            items.append(item)
        }
        let last = try #require(items.last)
        let marker = "org.nspasteboard.ConcealedType"
        #expect(last.setData(Data([1]), forType: .init(marker)))
        #expect(pasteboard.writeObjects(items))
        var reads = 0
        var adapter = PasteboardAdapter(pasteboard: pasteboard)
        adapter.payloadReadObserver = { _ in reads += 1 }
        guard case .concealed(let concealed) = adapter.captureOutcome() else {
            Issue.record("Privacy must remain a quiet whole-gesture exclusion even over resource limits")
            return
        }
        #expect(concealed.markerTypeIdentifier == marker)
        #expect(reads == 0)
    }

    @Test func lineageMetadataDoesNotConsumeTheRepresentationLimit() throws {
        let pasteboard = makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let item = NSPasteboardItem()
        let limit = HistoryLimits.standard.maximumRepresentationsPerCaptureOrRevision
        for index in 0..<limit {
            #expect(item.setData(Data([1]), forType: .init("com.clipy.tests.limit.\(index)")))
        }
        let id = HistoryItemID(rawValue: UUID())
        #expect(item.setData(PasteboardLineageHint.encode(id), forType: .init(PasteboardLineageHint.typeIdentifier)))
        #expect(pasteboard.writeObjects([item]))
        let capture = try #require(PasteboardAdapter(pasteboard: pasteboard).capture())
        #expect(capture.representations.count == limit)
        #expect(capture.origin.lineageHint == id)
    }

    @Test func oversizedRepresentationStopsBeforeTheNextItemProvider() throws {
        let pasteboard = makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let first = NSPasteboardItem()
        let second = NSPasteboardItem()
        let type = NSPasteboard.PasteboardType("com.clipy.tests.oversized")
        #expect(first.setData(Data(repeating: 0x61,
            count: HistoryLimits.standard.maximumRepresentationBytes + 1), forType: type))
        #expect(second.setData(Data([1]), forType: .string))
        #expect(pasteboard.writeObjects([first, second]))
        var reads: [String] = []
        var adapter = PasteboardAdapter(pasteboard: pasteboard)
        adapter.payloadReadObserver = { reads.append($0) }
        guard case .unsupportedMultiItem = adapter.captureOutcome() else {
            Issue.record("An oversized representation must reject the entire gesture")
            return
        }
        #expect(reads == [type.rawValue])
    }

    @Test func aggregateByteLimitStopsFurtherProvidersAndExposesNoPartialCapture() throws {
        let pasteboard = makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let limit = HistoryLimits.standard.maximumRepresentationBytes
        let bytes = Data(repeating: 0x61, count: limit)
        var items: [NSPasteboardItem] = []
        for index in 0..<4 {
            let item = NSPasteboardItem()
            #expect(item.setData(index < 2 ? bytes : Data([1]),
                forType: .init("com.clipy.tests.aggregate.\(index)")))
            items.append(item)
        }
        #expect(pasteboard.writeObjects(items))
        var reads: [String] = []
        var adapter = PasteboardAdapter(pasteboard: pasteboard)
        adapter.payloadReadObserver = { reads.append($0) }
        guard case .unsupportedMultiItem = adapter.captureOutcome() else {
            Issue.record("Cross-item bytes exceeding the capture budget must reject the complete gesture")
            return
        }
        #expect(reads == (0..<3).map { "com.clipy.tests.aggregate.\($0)" })
    }
}
#endif
