/// PasteboardAdapter acceptance gates (docs/roadmap/04-pasteboardadapter.md
/// "Acceptance"):
///
/// - Capture freezes all retainable typed representations of the pasteboard
///   item (03a §4; 01 §5.1).
/// - Multiple pasteboard items produce an explicit unsupported shape before
///   payload access; the adapter never flattens duplicate types or silently
///   presents the first item as the complete clipboard gesture (CLIP-7).
/// - A sibling `org.nspasteboard.ConcealedType` — and every other marker in
///   the configured private/transient set — short-circuits the WHOLE item
///   before any payload accessor runs; the explicit concealed outcome has
///   no retainable bytes for a caller to submit.
/// - `write(_:)` stages the payload's Effective Content representations and
///   lineage hint on one new item before touching the pasteboard, then makes
///   one framework write attempt; the hint decodes back into
///   `CopyOriginObservation.lineageHint` on the next capture (03b §9; 04
///   §8; 01 §5.6). End-to-end coalescing via the hint is proven by WS4
///   through History, not here.
/// - The observer captures the current contents immediately on start, then
///   fires the handler once per distinct `changeCount` bump.
/// - A start/end `changeCount` mismatch discards every representation read
///   during that attempt and produces an explicit content-free retry outcome;
///   the complete-capture convenience returns nil (REVIEW Card 5B).
/// - Failure is explicit, never silent (audit SPEC-IMPL-005,
///   docs/reviews/2026-08-20-clipy-maccy-audit/02-spec-implementation.md):
///   a declared-but-unavailable type is recorded by the
///   `CaptureOutcome.declaredUnavailable` case instead of being silently
///   dropped, and `write(_:)` throws
///   `PasteboardWriteFailure` for refused item staging or a refused whole-item
///   write instead of ignoring framework Booleans. A Debug-only package,
///   immutable failure configuration injects unavailable reads, staging
///   rejection, and completed-item rejection; it is absent from Release and
///   unavailable to ordinary adapter clients (REVIEW Card 5D).
///
/// Every test uses a private `NSPasteboard(name:)` with a unique name, so
/// the suite never reads or mutates the user's clipboard.
import AppKit
import Foundation
import HistoryCore
import Testing
@testable import PasteboardAdapter

// MARK: - Fixtures

/// The six exact marker strings, pinned literally so any drift in
/// `PasteboardMarkers.concealedTypeIdentifiers` fails here (they mirror
/// `IngestPreparationActor.standardTransientTypeIdentifiers`).
private let concealmentMarkers: [String] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "de.petermaurer.TransientPasteboardType",
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
]

/// A fresh, uniquely named private pasteboard per test.
@MainActor
private func makePasteboard() -> NSPasteboard {
    NSPasteboard(
        name: NSPasteboard.Name("com.clipy.pasteboardadaptertests." + UUID().uuidString)
    )
}

/// Spins the main run loop in short slices until `condition` holds or
/// `timeout` elapses, servicing the observer's main-RunLoop `Timer` (whose
/// block polls synchronously on the main actor) while the synchronous test
/// body waits. Returns whether the condition was met.
@MainActor
private func spinMainRunLoop(until condition: () -> Bool, timeout: TimeInterval = 2) -> Bool {
    let deadline = Date().addingTimeInterval(timeout)
    while Date() < deadline {
        if condition() { return true }
        _ = RunLoop.main.run(mode: .default, before: Date(timeIntervalSinceNow: 0.02))
    }
    return condition()
}

// MARK: - Capture freeze (03a §4; roadmap 04 acceptance 1)

@Test @MainActor
func captureFreezesEveryRetainableTypedRepresentation() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    pasteboard.setData(Data("<b>rich</b>".utf8), forType: NSPasteboard.PasteboardType("public.html"))

    let observedAt = Date(timeIntervalSince1970: 1_000_000)
    let capture = PasteboardAdapter(pasteboard: pasteboard).capture(observedAt: observedAt)

    #expect(capture != nil)
    #expect(capture?.observedAt == observedAt)
    #expect(capture?.isConcealed == false)
    #expect(capture?.origin.lineageHint == nil)
    #expect(capture?.representations.count == 2)
    #expect(
        capture?.representations.contains {
            $0.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue
                && $0.bytes == Data("plain".utf8)
        } == true
    )
    #expect(
        capture?.representations.contains {
            $0.typeIdentifier == "public.html" && $0.bytes == Data("<b>rich</b>".utf8)
        } == true
    )
}

#if DEBUG
@Test @MainActor
func pasteboardChangeBetweenRepresentationReadsProducesContentFreeRetryOutcome() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("old plain".utf8), forType: .string)
    pasteboard.setData(
        Data("<b>old rich</b>".utf8),
        forType: NSPasteboard.PasteboardType("public.html")
    )
    let startChangeCount = pasteboard.changeCount
    var didReplaceContents = false
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadCompletionHook = { _ in
        guard !didReplaceContents else { return }
        didReplaceContents = true
        pasteboard.clearContents()
        pasteboard.setData(Data("new plain".utf8), forType: .string)
        pasteboard.setData(
            Data("<b>new rich</b>".utf8),
            forType: NSPasteboard.PasteboardType("public.html")
        )
    }

    let outcome = try #require(adapter.captureOutcome())

    #expect(didReplaceContents)
    guard case let .changedDuringRead(changed) = outcome else {
        Issue.record("expected a content-free changed-during-read outcome")
        return
    }
    #expect(changed.startChangeCount == startChangeCount)
    #expect(changed.endChangeCount == pasteboard.changeCount)
    #expect(changed.endChangeCount != changed.startChangeCount)
    // Neither the old first read nor the new board may enter History as a
    // complete snapshot. Ownership change is its own retry reason, not an
    // unavailable-type diagnosis.
}

@Test @MainActor
func completeCaptureConvenienceRejectsPasteboardChangedDuringRead() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("old plain".utf8), forType: .string)
    pasteboard.setData(
        Data("<b>old rich</b>".utf8),
        forType: NSPasteboard.PasteboardType("public.html")
    )
    var didReplaceContents = false
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadCompletionHook = { _ in
        guard !didReplaceContents else { return }
        didReplaceContents = true
        pasteboard.clearContents()
        pasteboard.setString("new plain", forType: .string)
    }

    #expect(adapter.capture() == nil)
    #expect(didReplaceContents)
}
#endif

@Test @MainActor
func captureOfEmptyPasteboardReturnsNil() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()

    #expect(PasteboardAdapter(pasteboard: pasteboard).capture() == nil)
}

#if DEBUG
@Test @MainActor
func multipleItemsAreExplicitlyUnsupportedBeforeAnyPayloadRead() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()

    let first = NSPasteboardItem()
    #expect(first.setData(Data("first".utf8), forType: .string))
    #expect(
        first.setData(
            Data("first-custom".utf8),
            forType: NSPasteboard.PasteboardType("com.clipy.tests.first")
        )
    )
    let second = NSPasteboardItem()
    #expect(second.setData(Data("second".utf8), forType: .string))
    #expect(
        second.setData(
            Data("second-custom".utf8),
            forType: NSPasteboard.PasteboardType("com.clipy.tests.second")
        )
    )
    #expect(pasteboard.writeObjects([first, second]))

    var payloadAccessorCalls: [String] = []
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadObserver = { typeIdentifier in
        payloadAccessorCalls.append(typeIdentifier)
    }

    let outcome = try #require(adapter.captureOutcome())

    #expect(payloadAccessorCalls.isEmpty)
    guard case let .unsupportedMultiItem(unsupported) = outcome else {
        Issue.record("expected the unsupported multi-item outcome")
        return
    }
    #expect(unsupported.itemCount == 2)
    #expect(unsupported.changeCount == pasteboard.changeCount)
    // The convenience API must not disguise the first item as the complete
    // clipboard gesture when the public capture model cannot preserve the
    // two item boundaries or their duplicate string representations.
    #expect(adapter.capture() == nil)
    #expect(payloadAccessorCalls.isEmpty)
}
#endif

// MARK: - Concealment markers (roadmap 04 acceptance 2)

#if DEBUG
@Test @MainActor
func declaredConcealmentMarkerShortCircuitsBeforeReadingLargeSiblingPayload() throws {
    let marker = "org.nspasteboard.ConcealedType"
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(
        Data(repeating: 0x73, count: 5 * 1_024 * 1_024),
        forType: .string
    )
    pasteboard.setData(
        Data("marker".utf8),
        forType: NSPasteboard.PasteboardType(marker)
    )
    var payloadAccessorCalls: [String] = []
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadObserver = { typeIdentifier in
        payloadAccessorCalls.append(typeIdentifier)
    }

    let outcome = try #require(adapter.captureOutcome())

    #expect(payloadAccessorCalls.isEmpty)
    guard case let .concealed(concealed) = outcome else {
        Issue.record("expected the concealed-before-bytes outcome")
        return
    }
    #expect(concealed.markerTypeIdentifier == marker)
    #expect(concealed.changeCount == pasteboard.changeCount)
    #expect(adapter.capture() == nil)
    #expect(payloadAccessorCalls.isEmpty)
}

@Test @MainActor
func payloadReadInstrumentationObservesUnmarkedCaptureWithoutChangingIt() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("ordinary".utf8), forType: .string)
    var payloadAccessorCalls: [String] = []
    var adapter = PasteboardAdapter(pasteboard: pasteboard)
    adapter.payloadReadObserver = { typeIdentifier in
        payloadAccessorCalls.append(typeIdentifier)
    }

    let outcome = try #require(adapter.captureOutcome())

    #expect(payloadAccessorCalls == [NSPasteboard.PasteboardType.string.rawValue])
    guard case let .complete(complete) = outcome else {
        Issue.record("expected the stable complete outcome")
        return
    }
    #expect(complete.changeCount == pasteboard.changeCount)
    #expect(complete.capture.isConcealed == false)
    #expect(complete.capture.representations == [
        CapturedRepresentation(
            typeIdentifier: NSPasteboard.PasteboardType.string.rawValue,
            bytes: Data("ordinary".utf8)
        )
    ])
}
#endif

@Test @MainActor
func everyConcealmentMarkerMarksTheWholeCaptureConcealed() {
    for marker in concealmentMarkers {
        let pasteboard = makePasteboard()
        pasteboard.clearContents()
        pasteboard.setData(Data("sensitive".utf8), forType: .string)
        pasteboard.setData(Data("marker".utf8), forType: NSPasteboard.PasteboardType(marker))

        guard let outcome = PasteboardAdapter(pasteboard: pasteboard).captureOutcome() else {
            Issue.record("expected concealed outcome for \(marker)")
            continue
        }

        guard case let .concealed(concealed) = outcome else {
            Issue.record("expected concealed outcome for \(marker)")
            continue
        }
        #expect(concealed.markerTypeIdentifier == marker, "\(marker)")
        #expect(concealed.changeCount == pasteboard.changeCount, "\(marker)")
        // Whole-item privacy semantics: declared types are enough to reject
        // this observation. The case has no capture field, so sibling bytes
        // cannot be retained or accidentally submitted by a caller.
    }
}

@Test @MainActor
func marksConcealedRecognizesExactlyTheMarkerSet() {
    for marker in concealmentMarkers {
        #expect(PasteboardMarkers.marksConcealed([marker]), "\(marker)")
        #expect(
            PasteboardMarkers.marksConcealed(["public.utf8-plain-text", marker]),
            "\(marker)"
        )
    }
    #expect(!PasteboardMarkers.marksConcealed(["public.utf8-plain-text", "public.html"]))
    #expect(!PasteboardMarkers.marksConcealed([]))
    #expect(PasteboardMarkers.concealedTypeIdentifiers.count == 6)
    #expect(concealmentMarkers.allSatisfy { PasteboardMarkers.concealedTypeIdentifiers.contains($0) })
}

// MARK: - Lineage hint codec (03b §9; roadmap 04 acceptance 3, codec half)

@Test @MainActor
func lineageHintCodecRoundTripsAndRejectsMalformedData() {
    #expect(PasteboardLineageHint.typeIdentifier == "com.clipy.lineageHint")

    let id = HistoryItemID(rawValue: UUID())
    #expect(PasteboardLineageHint.encode(id) == Data(id.rawValue.uuidString.utf8))
    #expect(PasteboardLineageHint.decode(PasteboardLineageHint.encode(id)) == id)

    #expect(PasteboardLineageHint.decode(Data()) == nil)
    #expect(PasteboardLineageHint.decode(Data("not-a-uuid".utf8)) == nil)
    #expect(
        PasteboardLineageHint.decode(Data("AB108DC6-779D-4C78-B7F5-45BE50EF1CD8".utf8)) != nil
    )
}

// MARK: - Paste write + hint round-trip (03b §9; 04 §8; roadmap 04 acceptance 3)

@Test @MainActor
func writeRoundTripsLineageHintIntoCaptureOrigin() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    let adapter = PasteboardAdapter(pasteboard: pasteboard)

    let id = HistoryItemID(rawValue: UUID())
    let payload = PastePayload(
        item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
        representations: [
            HistoryRepresentation(typeIdentifier: "public.utf8-plain-text", bytes: Data("Clipy".utf8)),
            HistoryRepresentation(typeIdentifier: "public.html", bytes: Data("<b>Clipy</b>".utf8)),
        ],
        lineageHint: id
    )

    try adapter.write(payload)

    let capture = adapter.capture()
    #expect(capture != nil)
    #expect(capture?.origin.lineageHint == id)
    #expect(capture?.isConcealed == false)
    // The hint marker is metadata: it must not survive as a retained
    // representation of the re-captured paste.
    #expect(capture?.representations.count == 2)
    #expect(
        capture?.representations.contains {
            $0.typeIdentifier == PasteboardLineageHint.typeIdentifier
        } == false
    )
}

@Test @MainActor
func writeReplacesPriorContentWithOneCompleteItem() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("stale".utf8), forType: NSPasteboard.PasteboardType("com.clipy.tests.stale"))
    let adapter = PasteboardAdapter(pasteboard: pasteboard)

    let id = HistoryItemID(rawValue: UUID())
    try adapter.write(
        PastePayload(
            item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
            representations: [
                HistoryRepresentation(
                    typeIdentifier: "public.utf8-plain-text",
                    bytes: Data("fresh".utf8)
                ),
                HistoryRepresentation(
                    typeIdentifier: "public.html",
                    bytes: Data("<b>fresh</b>".utf8)
                )
            ],
            lineageHint: id
        )
    )

    #expect(pasteboard.pasteboardItems?.count == 1)
    let item = pasteboard.pasteboardItems?.first
    let typeIdentifiers = item?.types.map { $0.rawValue } ?? []
    #expect(typeIdentifiers.contains("public.utf8-plain-text"))
    #expect(typeIdentifiers.contains("public.html"))
    #expect(typeIdentifiers.contains(PasteboardLineageHint.typeIdentifier))
    #expect(!typeIdentifiers.contains("com.clipy.tests.stale"))
    #expect(item?.data(forType: .string) == Data("fresh".utf8))
    #expect(
        item?.data(forType: NSPasteboard.PasteboardType("public.html"))
            == Data("<b>fresh</b>".utf8)
    )
    #expect(
        item?.data(forType: NSPasteboard.PasteboardType(PasteboardLineageHint.typeIdentifier))
            == PasteboardLineageHint.encode(id)
    )
}

// MARK: - Partial-freeze record + typed write failure (audit SPEC-IMPL-005)

#if DEBUG
@Test @MainActor
func captureRecordsADeclaredButUnavailableTypeAsAPartialFreeze() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    pasteboard.setData(Data("<b>rich</b>".utf8), forType: NSPasteboard.PasteboardType("public.html"))
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            unavailableTypeIdentifiers: ["public.html"]
        )
    )

    guard let outcome = adapter.captureOutcome() else {
        Issue.record("expected the declared-unavailable partial outcome")
        return
    }

    // The nil-data type is RECORDED, never silently dropped. The available
    // representation is still frozen, and the closed case marks it partial
    // without claiming why the system did not vend those bytes.
    guard case let .declaredUnavailable(partial) = outcome else {
        Issue.record("expected the declared-unavailable partial outcome")
        return
    }
    #expect(partial.unavailableTypeIdentifiers == ["public.html"])
    #expect(partial.changeCount == pasteboard.changeCount)
    #expect(partial.partialCapture.representations.count == 1)
    #expect(
        partial.partialCapture.representations.first?.typeIdentifier
            == NSPasteboard.PasteboardType.string.rawValue
    )
    #expect(
        partial.partialCapture.representations.first?.bytes == Data("plain".utf8)
    )
    #expect(adapter.capture() == nil)
}
#endif

@Test @MainActor
func captureOfAFullyObservedItemIsACompleteOutcome() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    let stableChangeCount = pasteboard.changeCount

    let observedAt = Date(timeIntervalSince1970: 1_760_000_000)
    guard let outcome = PasteboardAdapter(pasteboard: pasteboard)
        .captureOutcome(observedAt: observedAt) else {
        Issue.record("expected the stable complete outcome")
        return
    }

    guard case let .complete(complete) = outcome else {
        Issue.record("expected the stable complete outcome")
        return
    }
    #expect(complete.changeCount == stableChangeCount)
    // The convenience half drops the record but freezes the same bytes;
    // both calls share one injected observedAt so the comparison is
    // deterministic (the default Date() stamps would differ sub-second).
    #expect(
        PasteboardAdapter(pasteboard: pasteboard)
            .capture(observedAt: observedAt) == complete.capture
    )
}

#if DEBUG
@Test @MainActor
func everyUnavailableRepresentationProducesAnExplicitPartialOutcome() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            unavailableTypeIdentifiers: [
                NSPasteboard.PasteboardType.string.rawValue
            ]
        )
    )

    guard let outcome = adapter.captureOutcome() else {
        Issue.record("expected the all-unavailable partial outcome")
        return
    }

    // The observer has consumed this changeCount, so an all-unavailable
    // gesture must remain distinguishable from a cleared pasteboard.
    guard case let .declaredUnavailable(partial) = outcome else {
        Issue.record("expected the all-unavailable partial outcome")
        return
    }
    #expect(
        partial.unavailableTypeIdentifiers
            == [NSPasteboard.PasteboardType.string.rawValue]
    )
    #expect(partial.partialCapture.representations.isEmpty)
    #expect(partial.changeCount == pasteboard.changeCount)
    #expect(adapter.capture() == nil)
}

@Test @MainActor
func rejectedRepresentationStagingLeavesExistingPasteboardUntouched() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    let sentinelType = NSPasteboard.PasteboardType("com.clipy.tests.sentinel")
    let sentinelBytes = Data("keep me".utf8)
    pasteboard.setData(sentinelBytes, forType: sentinelType)
    let sentinelChangeCount = pasteboard.changeCount
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            rejectedWriteTypeIdentifiers: ["public.html"]
        )
    )

    let id = HistoryItemID(rawValue: UUID())
    let payload = PastePayload(
        item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
        representations: [
            HistoryRepresentation(typeIdentifier: "public.utf8-plain-text", bytes: Data("Clipy".utf8)),
            HistoryRepresentation(typeIdentifier: "public.html", bytes: Data("<b>Clipy</b>".utf8)),
        ],
        lineageHint: id
    )

    // The typed failure names every refused staged type identifier.
    do {
        try adapter.write(payload)
        Issue.record("SPEC-IMPL-005: expected PasteboardWriteFailure")
    } catch let failure as PasteboardWriteFailure {
        #expect(
            failure == .representationsRejected(typeIdentifiers: ["public.html"]),
            "SPEC-IMPL-005: the failure names the refused representation"
        )
    }

    // All setters target an unbound in-memory item. A staging failure is
    // reported before clear/writeObjects, so even changeCount is unchanged.
    #expect(pasteboard.changeCount == sentinelChangeCount)
    #expect(pasteboard.pasteboardItems?.count == 1)
    let item = pasteboard.pasteboardItems?.first
    #expect(item?.types.map(\.rawValue) == [sentinelType.rawValue])
    #expect(item?.data(forType: sentinelType) == sentinelBytes)
    #expect(item?.data(forType: .string) == nil)
    #expect(item?.data(forType: NSPasteboard.PasteboardType("public.html")) == nil)
    #expect(
        item?.data(forType: NSPasteboard.PasteboardType(PasteboardLineageHint.typeIdentifier))
            == nil
    )
}

@Test @MainActor
func rejectedLineageHintStagingLeavesExistingPasteboardUntouched() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    let sentinelType = NSPasteboard.PasteboardType("com.clipy.tests.sentinel")
    let sentinelBytes = Data("keep me too".utf8)
    pasteboard.setData(sentinelBytes, forType: sentinelType)
    let sentinelChangeCount = pasteboard.changeCount
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            rejectedWriteTypeIdentifiers: [
                PasteboardLineageHint.typeIdentifier
            ]
        )
    )

    let id = HistoryItemID(rawValue: UUID())
    let payload = PastePayload(
        item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
        representations: [
            HistoryRepresentation(
                typeIdentifier: "public.utf8-plain-text",
                bytes: Data("Clipy".utf8)
            )
        ],
        lineageHint: id
    )

    do {
        try adapter.write(payload)
        Issue.record("SPEC-IMPL-005: expected PasteboardWriteFailure")
    } catch let failure as PasteboardWriteFailure {
        #expect(
            failure == .representationsRejected(
                typeIdentifiers: [PasteboardLineageHint.typeIdentifier]
            ),
            "SPEC-IMPL-005: a hint refusal is named like any other type"
        )
    }

    #expect(pasteboard.changeCount == sentinelChangeCount)
    #expect(pasteboard.pasteboardItems?.count == 1)
    let item = pasteboard.pasteboardItems?.first
    #expect(item?.types.map(\.rawValue) == [sentinelType.rawValue])
    #expect(item?.data(forType: sentinelType) == sentinelBytes)
    #expect(item?.data(forType: .string) == nil)
    #expect(
        item?.data(forType: NSPasteboard.PasteboardType(PasteboardLineageHint.typeIdentifier))
            == nil
    )
}

@Test @MainActor
func rejectedWholeItemIsReportedAfterClearingThePasteboard() throws {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    let sentinelType = NSPasteboard.PasteboardType("com.clipy.tests.sentinel")
    pasteboard.setData(Data("not retained".utf8), forType: sentinelType)
    let sentinelChangeCount = pasteboard.changeCount
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            rejectCompletedItem: true
        )
    )

    let id = HistoryItemID(rawValue: UUID())
    let payload = PastePayload(
        item: HistoryItemReference(id: id, contentVersion: ContentVersion(rawValue: 1)),
        representations: [
            HistoryRepresentation(
                typeIdentifier: "public.utf8-plain-text",
                bytes: Data("Clipy".utf8)
            )
        ],
        lineageHint: id
    )

    do {
        try adapter.write(payload)
        Issue.record("SPEC-IMPL-005: expected whole-item write rejection")
    } catch let failure as PasteboardWriteFailure {
        #expect(failure == .itemRejected)
    }

    // Whole-item refusal happens after clearContents(). There is no rollback
    // contract: this deterministic fixture has advanced and is now empty.
    #expect(pasteboard.changeCount > sentinelChangeCount)
    #expect((pasteboard.pasteboardItems ?? []).isEmpty)
}
#endif

#if DEBUG
@Test @MainActor
func observerDeliversAPartialOutcomeForTheCompositionToJudge() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setData(Data("plain".utf8), forType: .string)
    pasteboard.setData(Data("<b>rich</b>".utf8), forType: NSPasteboard.PasteboardType("public.html"))
    let adapter = PasteboardAdapter(
        pasteboard: pasteboard,
        failureSimulation: PasteboardFailureSimulation(
            unavailableTypeIdentifiers: ["public.html"]
        )
    )
    let observer = PasteboardObserver(adapter: adapter, pollInterval: 0.05)

    var received: [CaptureOutcome] = []
    observer.start { outcome in
        received.append(outcome)
    }
    defer { observer.stop() }

    // start delivers the CURRENT contents synchronously: the partial
    // freeze reaches the handler owner (the composition root drops it
    // rather than admitting partial Canonical Content, 01 §5.1).
    #expect(received.count == 1)
    guard let firstOutcome = received.first else {
        Issue.record("expected the observer to deliver an outcome")
        return
    }
    guard case let .declaredUnavailable(partial) = firstOutcome else {
        Issue.record("expected the observer to deliver the partial outcome")
        return
    }
    #expect(partial.unavailableTypeIdentifiers == ["public.html"])
    #expect(partial.partialCapture.representations.count == 1)
}
#endif

// MARK: - Observation (01 §5.1; roadmap 04 deliverable 3, acceptance 4)

@Test @MainActor
func observerCapturesImmediatelyThenFiresOncePerChangeCountBump() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setString("first", forType: .string)
    let observer = PasteboardObserver(
        adapter: PasteboardAdapter(pasteboard: pasteboard),
        pollInterval: 0.05
    )

    var received: [ClipboardCapture] = []
    observer.start { outcome in
        if case let .complete(complete) = outcome {
            received.append(complete.capture)
        }
    }

    // start delivers the CURRENT contents synchronously before returning.
    #expect(received.count == 1)
    #expect(
        received.first?.representations.contains {
            $0.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue
                && $0.bytes == Data("first".utf8)
        } == true
    )

    // A real change (clear + write bumps the change count) is delivered
    // once, with the new contents.
    pasteboard.clearContents()
    pasteboard.setString("second", forType: .string)
    #expect(spinMainRunLoop { received.count >= 2 })
    #expect(
        received.last?.representations.contains {
            $0.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue
                && $0.bytes == Data("second".utf8)
        } == true
    )

    // A change that leaves nothing retainable is recorded but not
    // delivered: the handler fires only for non-nil captures.
    pasteboard.clearContents()
    let deliveredEmptyChange = spinMainRunLoop(until: { received.count >= 3 }, timeout: 0.4)
    #expect(!deliveredEmptyChange)

    observer.stop()
}

@Test @MainActor
func observerStopHaltsDelivery() {
    let pasteboard = makePasteboard()
    pasteboard.clearContents()
    pasteboard.setString("first", forType: .string)
    let observer = PasteboardObserver(
        adapter: PasteboardAdapter(pasteboard: pasteboard),
        pollInterval: 0.05
    )

    var received: [ClipboardCapture] = []
    observer.start { outcome in
        if case let .complete(complete) = outcome {
            received.append(complete.capture)
        }
    }
    observer.stop()

    pasteboard.clearContents()
    pasteboard.setString("after-stop", forType: .string)
    let deliveredAfterStop = spinMainRunLoop(until: { received.count >= 2 }, timeout: 0.4)
    #expect(!deliveredAfterStop)
    #expect(received.count == 1)
}
